# Generated by Django 6.0 on 2025-12-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0018_grant_operatingsystem_to_provisioner"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="ngfw_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Deploy VM-Series NGFW inline between Kali and Victim",
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="ngfw_instance_id",
            field=models.CharField(
                blank=True, default="", help_text="NGFW EC2 instance ID", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="ngfw_trust_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="NGFW trust interface IP (Victim-facing)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="ngfw_untrust_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="NGFW untrust interface IP (Kali-facing)",
                null=True,
            ),
        ),
    ]
