# Generated by Django 6.0 on 2025-12-28 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0024_range_dc_agent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrataConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for this config", max_length=255
                    ),
                ),
                (
                    "scm_folder_name",
                    models.CharField(
                        help_text="SCM folder name (Configuration > Folders in SCM)",
                        max_length=255,
                    ),
                ),
                (
                    "scm_pin_id",
                    models.CharField(
                        help_text="Auto-registration PIN ID (Assets > Device Certificates in SCM)",
                        max_length=255,
                    ),
                ),
                (
                    "scm_pin_value",
                    models.CharField(
                        help_text="Auto-registration PIN value", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strata_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strata Config",
                "verbose_name_plural": "Strata Configs",
                "ordering": ["-created_at"],
            },
        ),
    ]
