# Generated by Django 6.0 on 2025-12-28 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0025_strata_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="strata_config",
            field=models.ForeignKey(
                blank=True,
                help_text="SCM config for NGFW bootstrap (PIN-based registration)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ranges",
                to="mission_control.strataconfig",
            ),
        ),
        migrations.AlterField(
            model_name="agentconfig",
            name="name",
            field=models.CharField(help_text="User-friendly name", max_length=255),
        ),
        migrations.AlterField(
            model_name="agentconfig",
            name="s3_key",
            field=models.CharField(help_text="S3 object key", max_length=500),
        ),
        migrations.AlterField(
            model_name="range",
            name="ngfw_config",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use strata_config instead. Panorama-based NGFW config.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ranges",
                to="mission_control.ngfwconfig",
            ),
        ),
    ]
