# Generated by Django 6.0 on 2025-12-30 10:34

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0029_drop_strata_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="gwlb_endpoint_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GWLB endpoint ID for this range's NGFW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="instance_config",
            field=models.JSONField(
                blank=True,
                help_text="JSON array of instance configurations for Shifter Engine",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="NGFWDeploymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User-friendly name", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this credential expires (user sets at creation)",
                        null=True,
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time credential was validated against external system",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time credential was used for provisioning",
                        null=True,
                    ),
                ),
                (
                    "authcode",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="Authcode from CSP deployment profile (e.g., D9232090)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngfw_deployment_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NGFW Deployment Profile",
                "verbose_name_plural": "NGFW Deployment Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SCMCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User-friendly name", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this credential expires (user sets at creation)",
                        null=True,
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time credential was validated against external system",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time credential was used for provisioning",
                        null=True,
                    ),
                ),
                ("scm_folder_name", models.CharField(max_length=255)),
                ("scm_pin_id", models.CharField(max_length=255)),
                ("scm_pin_value", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "sls_region",
                    models.CharField(
                        choices=[
                            ("americas", "Americas"),
                            ("europe", "Europe"),
                            ("japan", "Japan"),
                            ("asiapacific", "Asia Pacific"),
                        ],
                        default="americas",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scm_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SCM Credential",
                "verbose_name_plural": "SCM Credentials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNGFW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User-friendly name", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_provisioned", "Not Provisioned"),
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready"),
                            ("starting", "Starting"),
                            ("active", "Active"),
                            ("stopping", "Stopping"),
                            ("stopped", "Stopped"),
                            ("deprovisioning", "Deprovisioning"),
                            ("failed", "Failed"),
                        ],
                        default="not_provisioned",
                        max_length=20,
                    ),
                ),
                ("instance_id", models.CharField(blank=True, max_length=32)),
                ("mgmt_eni_id", models.CharField(blank=True, max_length=32)),
                ("data_eni_id", models.CharField(blank=True, max_length=32)),
                ("management_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dataplane_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("gwlb_arn", models.CharField(blank=True, max_length=256)),
                ("target_group_arn", models.CharField(blank=True, max_length=256)),
                ("gwlb_service_name", models.CharField(blank=True, max_length=256)),
                ("serial_number", models.CharField(blank=True, max_length=32)),
                ("device_cert_status", models.CharField(blank=True, max_length=32)),
                ("xdr_configured", models.BooleanField(default=False)),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deployment_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ngfws",
                        to="mission_control.ngfwdeploymentprofile",
                    ),
                ),
                (
                    "scm_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ngfws",
                        to="mission_control.scmcredential",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngfws",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User NGFW",
                "verbose_name_plural": "User NGFWs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="range",
            name="ngfw",
            field=models.ForeignKey(
                blank=True,
                help_text="Persistent NGFW instance for this range",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ranges",
                to="mission_control.userngfw",
            ),
        ),
    ]
