"""Tests for the GCP private-service egress NetworkPolicy renderer."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest


def _load_module(module_filename: str, module_name: str):
    module_path = Path(__file__).resolve().parents[1] / module_filename
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _outputs(*, gke_services_cidr: str = "10.48.0.0/20") -> dict[str, object]:
    return {
        "control_plane_database": {
            "value": {
                "private_ip": "10.40.0.10",
                "port": 5432,
            }
        },
        "control_plane_cache": {
            "value": {
                "host": "10.40.0.20",
                "port": 6378,
                "tls_enabled": True,
            }
        },
        "guacamole_database": {
            "value": {
                "host": "10.40.0.11",
                "port": 5432,
                "database_name": "guacamole",
            }
        },
        "gke_services_cidr": {"value": gke_services_cidr},
    }


def test_render_emits_per_host_cidrs_and_protected_ports():
    """The generated NetworkPolicy must scope egress to per-endpoint /32
    CIDRs (matching the Helm chart's `privateServiceCidrs` flow) and allow
    only the DB / Redis / Memorystore-TLS ports — never broad RFC1918
    supernets (ADR-008-R4, ADR-008-R6, #959/#963)."""
    module = _load_module("render_private_service_netpol.py", "render_private_service_netpol")

    rendered = module.render_netpol(_outputs())

    # Header: matches the generated-file convention used by the rest of
    # the workflow.
    assert rendered.startswith("# This file is generated by")
    assert "kind: NetworkPolicy" in rendered
    assert "name: allow-platform-private-service-egress-generated" in rendered
    assert "namespace: shifter-platform" in rendered
    # Per-endpoint /32 ipBlocks — no broad supernets.
    assert "cidr: 10.40.0.10/32" in rendered  # Cloud SQL
    assert "cidr: 10.40.0.20/32" in rendered  # Memorystore
    assert "cidr: 10.40.0.11/32" in rendered  # Guacamole DB
    assert "cidr: 10.48.0.0/20" in rendered  # GKE services range
    # Negative: the RFC1918 supernets used by the static Kustomize base
    # earlier in development must never appear in the generated output.
    assert "10.0.0.0/8" not in rendered
    assert "172.16.0.0/12" not in rendered
    assert "192.168.0.0/16" not in rendered
    # Ports: only the documented DB/Redis ports.
    assert "port: 5432" in rendered
    assert "port: 6378" in rendered  # Memorystore TLS endpoint
    assert "port: 6379" in rendered  # Plaintext (compat) port


def test_render_deduplicates_overlapping_hosts():
    """Cloud SQL + Guacamole DB run on the same instance today (the host
    output is identical). Dedupe so the manifest doesn't carry duplicate
    ipBlocks."""
    module = _load_module("render_private_service_netpol.py", "render_private_service_netpol")

    outputs = _outputs()
    # Force the Guacamole DB onto the same host as the platform DB.
    outputs["guacamole_database"]["value"]["host"] = outputs["control_plane_database"]["value"]["private_ip"]

    rendered = module.render_netpol(outputs)

    # The /32 should appear once even though two outputs name the same host.
    assert rendered.count("cidr: 10.40.0.10/32") == 1


def test_render_rejects_missing_gke_services_cidr():
    """Empty or missing gke_services_cidr means the GKE services range
    won't be permitted egress — that breaks restricted.googleapis.com and
    private cluster service-to-service calls. Fail closed."""
    module = _load_module("render_private_service_netpol.py", "render_private_service_netpol")

    with pytest.raises(ValueError, match="gke_services_cidr"):
        module.render_netpol(_outputs(gke_services_cidr="   "))


def test_render_rejects_invalid_host():
    """Garbage in the Terraform output should fail at render time, not
    produce a malformed manifest the cluster would silently reject."""
    module = _load_module("render_private_service_netpol.py", "render_private_service_netpol")

    outputs = _outputs()
    outputs["control_plane_database"]["value"]["private_ip"] = "not-an-ip"

    with pytest.raises(ValueError):
        module.render_netpol(outputs)
