options {
    directory "/var/bind";
    listen-on { any; };
    allow-query { any; };
    allow-transfer { any; };
    recursion no;
};

zone "boreas-systems.ctf" {
    type master;
    file "/etc/bind/db.boreas-systems.ctf";
};

zone "boreas.local" {
    type master;
    file "/etc/bind/db.boreas.local";
};
