apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal
  namespace: shifter-platform
  labels:
    app.kubernetes.io/part-of: shifter
    app.kubernetes.io/component: portal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workers
  namespace: shifter-platform
  labels:
    app.kubernetes.io/part-of: shifter
    app.kubernetes.io/component: workers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctf-scheduler
  namespace: shifter-platform
  labels:
    app.kubernetes.io/part-of: shifter
    app.kubernetes.io/component: ctf-scheduler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: shifter-jobs
  labels:
    app.kubernetes.io/part-of: shifter
    app.kubernetes.io/component: provisioner
