# Generated by Django 6.0.6 on 2026-07-26 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Immutable public identifier; the only organization ID public surfaces accept.', unique=True)),
                ('name', models.CharField(help_text='Display name shown to members.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'workspaces_organization',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Immutable public identifier; the only workspace ID public surfaces accept.', unique=True)),
                ('name', models.CharField(help_text='Display name, unique within the organization.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Owning organization (intra-domain FK; always set).', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='workspaces.organization')),
                ('personal_for_user', models.OneToOneField(blank=True, help_text="Set when this is the user's personal compatibility workspace (#1325). NULL for ordinary shared workspaces; unique so a user has at most one.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspaces_workspace',
                'ordering': ['organization_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner')], help_text='Closed role code; the role-to-operation policy lives in workspaces.roles.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace membership',
                'verbose_name_plural': 'Workspace memberships',
                'db_table': 'workspaces_workspacemembership',
                'ordering': ['workspace_id', 'user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_workspace_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_membership_per_workspace_user'),
        ),
    ]
