# Generated by Django 6.0.6 on 2026-07-29 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_backfill_personal_workspaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], help_text='Closed role code; the role-to-operation policy lives in workspaces.roles.', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'admin', 'member'])), name='workspace_membership_role_valid'),
        ),
    ]
