# Generated by Django 6.0.6 on 2026-08-02 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspacemembership_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional organization description (PLAT-232). Empty string means unset.', max_length=2000),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_email',
            field=models.EmailField(blank=True, default='', help_text='Optional organization support email (PLAT-232). Empty string means unset.', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_url',
            field=models.URLField(blank=True, default='', help_text='Optional organization support URL (PLAT-232). Empty string means unset.', max_length=500),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin')], help_text='Closed organization role code; the authority seam lives in workspaces.services.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization membership',
                'verbose_name_plural': 'Organization memberships',
                'db_table': 'workspaces_organizationmembership',
                'ordering': ['organization_id', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uniq_org_membership_per_organization_user'), models.CheckConstraint(condition=models.Q(('role__in', ['admin'])), name='organization_membership_role_valid')],
            },
        ),
    ]
