# Generated by Django 6.0.6 on 2026-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_backfill_organization_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='Set when the workspace is archived; NULL for active workspaces. A reversible lifecycle marker only -- archival never deletes or rehomes ranges bound to the workspace (#1940, PLAT-233).', null=True),
        ),
    ]
