# Generated by Django 6.0.8 on 2026-08-12 16:52

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspace_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=32)),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspaces_workspaceinvitation',
                'ordering': ['workspace_id', '-created_at', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('workspace'), condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), name='uniq_current_invitation_workspace_email_ci'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'admin', 'member'])), name='workspace_invitation_role_valid'), models.CheckConstraint(condition=models.Q(('accepted_at__isnull', False), ('revoked_at__isnull', False), _negated=True), name='workspace_invitation_one_terminal_state'), models.CheckConstraint(condition=models.Q(('accepted_by__isnull', True), ('accepted_at__isnull', False), _connector='OR'), name='workspace_invitation_acceptance_complete')],
            },
        ),
    ]
