# Generated by Django 6.0.8 on 2026-08-11 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0007_workspaceinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="egress_policy",
            field=models.CharField(
                choices=[("status-quo", "Inherit deployment baseline"), ("none", "Zero egress (no outbound NAT path)")],
                default="status-quo",
                help_text="Workspace network egress selector (PLAT-238). The compatibility default 'status-quo' inherits the deployment baseline; 'none' requests the ADR-026 zero-egress (no outbound NAT path) posture for newly provisioned ranges. This is the contextual subset of the canonical installation.range_egress vocabulary; the workspace never stores CIDRs or provider configuration (ADR-017-R5).",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=models.Q(("egress_policy__in", frozenset(["none", "status-quo"]))),
                name="workspace_egress_policy_closed_vocabulary",
            ),
        ),
    ]
