# Generated by Django 6.0.8 on 2026-09-03 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspace_egress_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceQuotaDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('concurrent_ranges', 'Concurrent ranges'), ('member_seats', 'Member seats')], max_length=32)),
                ('limit_at_decision', models.PositiveIntegerField(help_text='Policy limit evaluated against.')),
                ('mode_at_decision', models.CharField(choices=[('advisory', 'Advisory (soft cap)'), ('enforcing', 'Enforcing (hard cap)')], max_length=16)),
                ('policy_revision', models.PositiveIntegerField(help_text='Policy revision evaluated against.')),
                ('usage_before', models.PositiveIntegerField(help_text='Usage observed before the requested delta.')),
                ('requested_delta', models.PositiveIntegerField(default=1, help_text='Units the action would add.')),
                ('outcome', models.CharField(choices=[('admitted', 'Admitted'), ('warned', 'Warned (soft cap applied)'), ('rejected', 'Rejected (hard cap applied)')], max_length=16)),
                ('reason_code', models.CharField(help_text='Bounded machine-readable reason.', max_length=64)),
                ('actor_type', models.CharField(blank=True, max_length=32)),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('correlation_key', models.CharField(blank=True, help_text='Stable per-action correlation key.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workspace', models.ForeignKey(help_text='Owning workspace (intra-domain FK).', on_delete=django.db.models.deletion.CASCADE, related_name='quota_decisions', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace quota decision',
                'verbose_name_plural': 'Workspace quota decisions',
                'db_table': 'workspaces_quota_decision',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='idx_quota_decision_ws_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('resource__in', frozenset(['concurrent_ranges', 'member_seats']))), name='quota_decision_resource_closed_vocabulary'), models.CheckConstraint(condition=models.Q(('outcome__in', frozenset(['admitted', 'rejected', 'warned']))), name='quota_decision_outcome_closed_vocabulary'), models.CheckConstraint(condition=models.Q(('mode_at_decision__in', frozenset(['advisory', 'enforcing']))), name='quota_decision_mode_closed_vocabulary')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('concurrent_ranges', 'Concurrent ranges'), ('member_seats', 'Member seats')], help_text='Closed resource code the limit applies to.', max_length=32)),
                ('limit', models.PositiveIntegerField(help_text='Maximum allowed usage for the resource (non-negative).')),
                ('mode', models.CharField(choices=[('advisory', 'Advisory (soft cap)'), ('enforcing', 'Enforcing (hard cap)')], help_text="'advisory' warns and records; 'enforcing' blocks the over-limit action.", max_length=16)),
                ('revision', models.PositiveIntegerField(default=1, help_text='Bumped on every policy change; pinned on each quota decision.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(help_text='Owning workspace (intra-domain FK).', on_delete=django.db.models.deletion.CASCADE, related_name='quota_policies', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace quota policy',
                'verbose_name_plural': 'Workspace quota policies',
                'db_table': 'workspaces_quota_policy',
                'ordering': ['workspace_id', 'resource'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'resource'), name='uniq_quota_policy_per_workspace_resource'), models.CheckConstraint(condition=models.Q(('resource__in', frozenset(['concurrent_ranges', 'member_seats']))), name='quota_policy_resource_closed_vocabulary'), models.CheckConstraint(condition=models.Q(('mode__in', frozenset(['advisory', 'enforcing']))), name='quota_policy_mode_closed_vocabulary')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceQuotaReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('concurrent_ranges', 'Concurrent ranges'), ('member_seats', 'Member seats')], max_length=32)),
                ('correlation_key', models.CharField(help_text='Stable per-action correlation key (e.g. request UUID).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, default=None, help_text='Set when the reservation is released on terminal convergence; NULL while open.', null=True)),
                ('workspace', models.ForeignKey(help_text='Owning workspace (intra-domain FK).', on_delete=django.db.models.deletion.CASCADE, related_name='quota_reservations', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace quota reservation',
                'verbose_name_plural': 'Workspace quota reservations',
                'db_table': 'workspaces_quota_reservation',
                'ordering': ['workspace_id', 'resource', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'resource', 'correlation_key'), name='uniq_quota_reservation_per_correlation'), models.CheckConstraint(condition=models.Q(('resource__in', frozenset(['concurrent_ranges', 'member_seats']))), name='quota_reservation_resource_closed_vocabulary')],
            },
        ),
    ]
