# Generated by Django 6.0 on 2026-01-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="range",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="range",
            name="dc_agent",
        ),
        migrations.RemoveField(
            model_name="range",
            name="instance_config",
        ),
        migrations.AddField(
            model_name="range",
            name="cms_user_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="User ID from CMS (may differ from Django user.id)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="range_config",
            field=models.JSONField(
                blank=True,
                help_text="Full RangeSpec from CMS (scenario_id, user_id, instances)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userngfw",
            name="name",
            field=models.CharField(help_text="User-friendly name", max_length=100),
        ),
    ]
