# Generated by Django 6.0 on 2026-01-07 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0003_move_userngfw_to_cms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="range",
            name="ngfw",
        ),
        migrations.CreateModel(
            name="NGFW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cms_ngfw_id",
                    models.PositiveIntegerField(
                        help_text="CMS NGFW.id for correlation (not FK)", unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready"),
                            ("starting", "Starting"),
                            ("active", "Active"),
                            ("stopping", "Stopping"),
                            ("stopped", "Stopped"),
                            ("deprovisioning", "Deprovisioning"),
                            ("deprovisioned", "Deprovisioned"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "ngfw_config",
                    models.JSONField(
                        blank=True,
                        help_text="Full InstanceSpec with nested NGFWAppSpec from CMS",
                        null=True,
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "mgmt_eni_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "data_eni_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("management_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dataplane_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("gwlb_arn", models.CharField(blank=True, default="", max_length=256)),
                (
                    "target_group_arn",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "gwlb_service_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "device_cert_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("xdr_configured", models.BooleanField(default=False)),
                (
                    "pulumi_stack",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pulumi stack name for this NGFW",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_ngfws",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NGFW",
                "verbose_name_plural": "NGFWs",
                "ordering": ["-created_at"],
            },
        ),
    ]
