# Generated by Django 6.0 on 2026-01-08

from django.db import migrations


class Migration(migrations.Migration):
    """Remove legacy NGFW model.

    The NGFW model has been replaced by the Request/Instance/App hierarchy
    using UUID-based correlation (request_id) instead of int-based ngfw_id.

    Provisioning state is now stored in engine_instance.state JSON field,
    and events use the unified publish_ngfw_event with correlation IDs.
    """

    dependencies = [
        ("engine", "0004_remove_range_ngfw_fk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NGFW",
        ),
    ]
