# Generated by Django 6.0 on 2026-01-08 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_remove_ngfw_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, unique=True)),
                ('request_type', models.CharField(choices=[('ngfw', 'NGFW')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, help_text='UUID from the spec', unique=True)),
                ('spec', models.JSONField(blank=True, help_text='Hydrated spec JSON from CMS (what was asked for)', null=True)),
                ('state', models.JSONField(blank=True, help_text='Infrastructure state (resource IDs, IPs, etc.)', null=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('attacker', 'Attacker'), ('victim', 'Victim'), ('dc', 'Domain Controller'), ('ngfw', 'NGFW')], db_index=True, max_length=20)),
                ('os_type', models.CharField(choices=[('kali', 'Kali Linux'), ('ubuntu', 'Ubuntu'), ('windows', 'Windows'), ('panos', 'PAN-OS')], max_length=20)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instantiations', to='engine.request')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, help_text='UUID from the spec', unique=True)),
                ('spec', models.JSONField(blank=True, help_text='Hydrated spec JSON from CMS (what was asked for)', null=True)),
                ('state', models.JSONField(blank=True, help_text='Infrastructure state (resource IDs, IPs, etc.)', null=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('app_type', models.CharField(choices=[('os', 'OS'), ('ngfw', 'NGFW'), ('agent', 'Agent'), ('other', 'Other')], db_index=True, max_length=20)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='engine.instance')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instantiations', to='engine.request')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'ordering': ['-created_at'],
            },
        ),
    ]
