# Generated by Django 6.0 on 2026-01-08 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_request_instance_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID from the spec', unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID from the spec', unique=True),
        ),
    ]
