# Generated by Django 6.0 on 2026-01-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0007_alter_app_uuid_alter_instance_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="request",
            field=models.ForeignKey(
                blank=True,
                help_text="Request that spawned this range (new pattern)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranges",
                to="engine.request",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="request_type",
            field=models.CharField(
                choices=[("range", "RANGE"), ("ngfw", "NGFW")],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
