# Generated by Django 6.0 on 2026-01-10 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0008_add_range_request_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="range",
            name="range_config",
            field=models.JSONField(
                blank=True,
                help_text="Full RangeSpec from CMS (scenario_id, user_id, subnets)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID from the spec",
                        unique=True,
                    ),
                ),
                (
                    "spec",
                    models.JSONField(
                        blank=True,
                        help_text="Hydrated spec JSON from CMS (what was asked for)",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        help_text="Infrastructure state (resource IDs, IPs, etc.)",
                        null=True,
                    ),
                ),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("destroyed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical subnet name from CyberScript DSL",
                        max_length=100,
                    ),
                ),
                (
                    "connected_to",
                    models.JSONField(
                        default=list,
                        help_text="List of subnet names this subnet connects to (for NGFW routes)",
                    ),
                ),
                (
                    "range",
                    models.ForeignKey(
                        blank=True,
                        help_text="Range this logical subnet belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logical_subnets",
                        to="engine.range",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instantiations",
                        to="engine.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logical Subnet",
                "verbose_name_plural": "Logical Subnets",
                "ordering": ["-created_at"],
            },
        ),
    ]
