# Generated by Django 6.0 on 2026-01-11 04:55

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    """Generate unique UUIDs for existing Range rows."""
    Range = apps.get_model("engine", "Range")
    for row in Range.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0009_add_logical_subnet_model"),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name="range",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for cross-service correlation",
                null=True,
            ),
        ),
        # Step 2: Generate unique UUIDs for existing rows
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
        # Step 3: Add unique constraint and make non-nullable
        migrations.AlterField(
            model_name="range",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for cross-service correlation",
                unique=True,
            ),
        ),
    ]
