# Generated by Django 6.0 on 2026-01-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0010_add_range_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="subnet",
            field=models.ForeignKey(
                blank=True,
                help_text="Logical subnet this instance belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="engine.subnet",
            ),
        ),
    ]
