# Generated by Django 6.0 on 2026-01-18 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0013_grant_select_on_engine_subnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="ngfw_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="NGFW Instance this range is attached to (for egress filtering)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_ranges",
                to="engine.instance",
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="gwlb_endpoint_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GWLB endpoint ID for this range's NGFW (AWS resource ID)",
                max_length=32,
            ),
        ),
    ]
