# Generated by Django 6.0 on 2026-02-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0014_add_range_ngfw_instance_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="range",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("ready", "Ready"),
                    ("pausing", "Pausing"),
                    ("paused", "Paused"),
                    ("resuming", "Resuming"),
                    ("destroying", "Destroying"),
                    ("destroyed", "Destroyed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
