# Generated by Django 6.0.6 on 2026-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0026_outbox_provisioner_select_and_last_error_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcesImageMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(choices=[("gce", "Google Compute Engine"), ("aws", "AWS EC2")], max_length=16),
                ),
                (
                    "source_name",
                    models.CharField(help_text="Authored ACES image source name (for example 'kali').", max_length=200),
                ),
                (
                    "source_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Authored source version; blank matches any version for this source_name.",
                        max_length=100,
                    ),
                ),
                (
                    "image_ref",
                    models.CharField(
                        help_text="Concrete provider image (GCE source_image / family URL, AWS AMI id, ...).",
                        max_length=500,
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional provider machine type; blank lets the backend size from resources/defaults.",
                        max_length=100,
                    ),
                ),
                (
                    "disk_size_gb",
                    models.PositiveIntegerField(
                        blank=True, help_text="Optional boot disk size (GB); blank uses the backend default.", null=True
                    ),
                ),
                (
                    "disk_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional provider disk type; blank uses the backend default.",
                        max_length=100,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled mappings do not resolve (realization fails loud); use instead of deleting to keep audit.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "engine_aces_image_mapping",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "source_name", "source_version"), name="unique_aces_image_mapping"
                    )
                ],
            },
        ),
    ]
