# Generated by Django 6.0.6 on 2026-07-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0028_provisioner_launch_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="instantiation_purpose",
            field=models.CharField(
                blank=True,
                help_text="Trusted instantiation purpose bound at provision (#1666); NULL for legacy/non-GCP",
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="range_backend",
            field=models.CharField(
                blank=True,
                help_text="Admitted GCP range backend bound at provision (#1666); NULL for legacy/non-GCP",
                max_length=8,
                null=True,
            ),
        ),
    ]
