# Generated by Django 6.0.6 on 2026-07-19 17:33

import django.db.models.deletion
from django.db import migrations, models


def grant_select(apps, schema_editor):
    """Grant provisioner_lambda read-only access to the delivery-binding table.

    SELECT only: the provisioner joins + verifies + realizes content from these
    rows at apply time but never writes them (the Engine create seam is the sole
    writer, #1564).
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("GRANT SELECT ON engine_aces_content_delivery_binding TO provisioner_lambda;")


def revoke_select(apps, schema_editor):
    """Revoke provisioner_lambda access from the delivery-binding table."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("REVOKE SELECT ON engine_aces_content_delivery_binding FROM provisioner_lambda;")


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0030_range_vpn_access_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcesContentDeliveryBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_address",
                    models.CharField(
                        help_text="Compiled ACES content resource address this binding identifies.", max_length=500
                    ),
                ),
                ("sha256", models.CharField(help_text="Lowercase hex sha256 of the delivered payload.", max_length=64)),
                (
                    "storage_key",
                    models.CharField(
                        help_text="Normalized content-addressed object key for the delivered payload.", max_length=500
                    ),
                ),
                ("byte_count", models.PositiveBigIntegerField(help_text="Size in bytes of the delivered payload.")),
                (
                    "binding_version",
                    models.PositiveIntegerField(help_text="DeliveryBinding schema version (rolling-deploy seam)."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "range",
                    models.ForeignKey(
                        help_text="Range this delivery binding is realized for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_delivery_bindings",
                        to="engine.range",
                    ),
                ),
            ],
            options={
                "db_table": "engine_aces_content_delivery_binding",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("range", "content_address"), name="unique_aces_content_delivery_binding"
                    )
                ],
            },
        ),
        migrations.RunPython(grant_select, revoke_select),
    ]
