# Generated by Django 6.0.6 on 2026-07-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0031_aces_content_delivery_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityDeclaration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        default="ctf", help_text="Producing layer (currently always 'ctf')", max_length=32
                    ),
                ),
                (
                    "event_ref",
                    models.UUIDField(
                        db_index=True, help_text="Upstream event identifier (opaque to the engine; no FK by design)"
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable event label at declaration time",
                        max_length=200,
                    ),
                ),
                (
                    "expected_concurrent_ranges",
                    models.PositiveIntegerField(
                        help_text="Ranges expected in flight at peak (participants plus spares)"
                    ),
                ),
                ("cohort_size", models.PositiveIntegerField(help_text="Participant cohort size at declaration time")),
                (
                    "window_start",
                    models.DateTimeField(
                        blank=True, help_text="Expected start of the provisioning/consumption window", null=True
                    ),
                ),
                (
                    "window_end",
                    models.DateTimeField(blank=True, help_text="Expected end of the consumption window", null=True),
                ),
                (
                    "resource_hints",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Shared-resource demand hints (agent mix, NGFW, LLM provider class and rates, ...)",
                    ),
                ),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "engine_capacity_declaration",
                "ordering": ["-declared_at"],
                "indexes": [models.Index(fields=["event_ref", "-declared_at"], name="engine_capa_event_r_422b58_idx")],
            },
        ),
    ]
