# Generated by Django 6.0.6 on 2026-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0036_grant_operation_io_to_provisioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='vpn_gateway_pool_slot',
            field=models.PositiveIntegerField(blank=True, help_text='Reserved GCP OpenVPN gateway SA pool slot (single-project pool)', null=True),
        ),
    ]
