# Generated by Django 6.0.6 on 2026-07-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0039_revoke_ngfw_app_grants_from_provisioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='workspace_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Workspace this range is scoped to (soft reference; see ADR-046).', null=True),
        ),
    ]
