# Generated by Django 6.0.6 on 2026-07-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0042_workspace_binding_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.UUIDField(db_index=True, help_text='Upstream event identifier (opaque to the engine; no FK by design)')),
                ('partition_name', models.CharField(help_text='Deployment-declared target partition this decision was made against', max_length=100)),
                ('policy_version', models.CharField(help_text='Fingerprint of the capacity catalog that produced the decision', max_length=64)),
                ('outcome', models.CharField(help_text='admitted | warning | indeterminate | rejected', max_length=20)),
                ('verdicts', models.JSONField(blank=True, default=list, help_text='Per-metric bounded reason codes; never raw provider limits or usage figures')),
                ('observed_at', models.DateTimeField(help_text='When the underlying provider readings were taken (not when we asked)')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'engine_capacity_assessment',
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['event_ref', '-assessed_at'], name='engine_capa_event_r_d2de2a_idx'), models.Index(fields=['partition_name', '-assessed_at'], name='engine_capa_partiti_06ec46_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapacityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.UUIDField(db_index=True, help_text='Upstream event identifier holding the reservation')),
                ('request_id', models.UUIDField(blank=True, db_index=True, help_text='Provisioning request correlation id, when the reservation is request-scoped', null=True)),
                ('partition_name', models.CharField(help_text='Partition the capacity is held in', max_length=100)),
                ('metric_name', models.CharField(help_text='Catalog metric the capacity is held against', max_length=100)),
                ('amount', models.FloatField(help_text="Amount of the metric's unit committed")),
                ('window_start', models.DateTimeField(help_text='Start of the window this reservation occupies')),
                ('window_end', models.DateTimeField(help_text='End of the window this reservation occupies')),
                ('released_at', models.DateTimeField(blank=True, help_text='Set when the reservation is released; released rows no longer consume headroom', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, help_text='Assessment that created this reservation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='engine.capacityassessment')),
            ],
            options={
                'db_table': 'engine_capacity_reservation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partition_name', 'metric_name', 'released_at'], name='engine_capa_partiti_046932_idx'), models.Index(fields=['event_ref', 'released_at'], name='engine_capa_event_r_ec8664_idx')],
            },
        ),
    ]
