# Generated by Django 6.0.6 on 2026-07-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_capacity_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.UUIDField(db_index=True, help_text='Event the drawing range belongs to')),
                ('draw_key', models.UUIDField(db_index=True, help_text='Stable identity of the thing drawing (participant, spare, or replacement). Known before the range exists, so admission can decide before creation and a retry of the same creation cannot draw twice.')),
                ('request_id', models.UUIDField(blank=True, db_index=True, help_text='Provisioning request id, attached after creation for correlation', null=True)),
                ('amount', models.FloatField(help_text='Amount drawn from the budget')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='Set when the draw is returned to its budget', null=True)),
            ],
            options={
                'db_table': 'engine_capacity_draw',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='capacityreservation',
            name='consumed',
            field=models.FloatField(default=0.0, help_text='Amount of the committed budget drawn down by admitted ranges'),
        ),
        migrations.AddField(
            model_name='capacityreservation',
            name='enforcement',
            field=models.CharField(default='advisory', help_text='Enforcement mode in force when the budget was sized (advisory | enforcing)', max_length=16),
        ),
        migrations.AddField(
            model_name='capacityreservation',
            name='unit_amount',
            field=models.FloatField(default=0.0, help_text='Amount one range draws from this budget when admitted'),
        ),
        migrations.AlterField(
            model_name='capacityreservation',
            name='amount',
            field=models.FloatField(help_text="Total amount of the metric's unit committed for the whole event"),
        ),
        migrations.AddConstraint(
            model_name='capacityreservation',
            constraint=models.CheckConstraint(condition=models.Q(('consumed__lte', models.F('amount'))), name='capacity_reservation_consumed_within_budget'),
        ),
        migrations.AddConstraint(
            model_name='capacityreservation',
            constraint=models.CheckConstraint(condition=models.Q(('consumed__gte', 0)), name='capacity_reservation_consumed_non_negative'),
        ),
        migrations.AddField(
            model_name='capacitydraw',
            name='reservation',
            field=models.ForeignKey(help_text='Budget this draw is taken from', on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='engine.capacityreservation'),
        ),
        migrations.AddIndex(
            model_name='capacitydraw',
            index=models.Index(fields=['draw_key', 'released_at'], name='engine_capa_draw_ke_2ec794_idx'),
        ),
        migrations.AddConstraint(
            model_name='capacitydraw',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('reservation', 'draw_key'), name='capacity_draw_one_open_per_key'),
        ),
    ]
