# Generated by Django 6.0.6 on 2026-07-28 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0048_raes_hard_cutover'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaesParticipantAccessBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_address', models.CharField(help_text='Compiled RAES provisioning node address the participant may reach.', max_length=500)),
                ('channel', models.CharField(help_text='Closed participant access channel (ssh/rdp).', max_length=32)),
                ('account_address', models.CharField(help_text='Compiled RAES account address the channel is brokered as.', max_length=500)),
                ('binding_version', models.PositiveIntegerField(help_text='ParticipantAccessBinding schema version (rolling-deploy seam).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('range', models.ForeignKey(help_text='Range this participant-access declaration is realized for.', on_delete=django.db.models.deletion.CASCADE, related_name='participant_access_bindings', to='engine.range')),
            ],
            options={
                'db_table': 'engine_raes_participant_access_binding',
                'constraints': [models.UniqueConstraint(fields=('range', 'target_address', 'channel'), name='unique_raes_participant_access_binding'), models.CheckConstraint(condition=models.Q(('binding_version', 1), models.Q(('target_address', ''), _negated=True), models.Q(('account_address', ''), _negated=True), ('channel__in', ['ssh', 'rdp'])), name='valid_raes_participant_access_binding_identity')],
            },
        ),
    ]
