# Generated by Django 6.0.6 on 2026-07-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0049_raesparticipantaccessbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionerlaunchintent',
            name='interrupt_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provisionerlaunchintent',
            name='interrupt_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionerlaunchintent',
            name='interrupt_last_error',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='provisionerlaunchintent',
            name='interrupt_next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionerlaunchintent',
            name='interrupt_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionerlaunchintent',
            name='interrupt_state',
            field=models.CharField(blank=True, choices=[('', 'None'), ('REQUESTED', 'Requested'), ('SUPPRESSED', 'Suppressed'), ('STOPPING', 'Stopping'), ('TERMINAL_ABSENT', 'Terminal absent'), ('DESTROY_ENQUEUED', 'Destroy enqueued'), ('IDENTITY_MISMATCH', 'Identity mismatch'), ('UNKNOWN', 'Unknown'), ('EXHAUSTED', 'Exhausted')], db_index=True, default='', max_length=24),
        ),
    ]
