# Generated by Django 6.0.6 on 2026-07-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0050_provisioner_launch_interrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='raesimagemapping',
            name='artifact_digest',
            field=models.CharField(blank=True, default='', help_text="Portable ArtifactIdentity sha256 digest ('sha256:'+64 hex); blank = legacy alias-only mapping.", max_length=71),
        ),
        migrations.AddField(
            model_name='raesimagemapping',
            name='artifact_id',
            field=models.CharField(blank=True, default='', help_text='Portable RAES ArtifactIdentity id this image realizes (blank = legacy alias-only mapping).', max_length=256),
        ),
        migrations.AddField(
            model_name='raesimagemapping',
            name='integrity_ref',
            field=models.CharField(blank=True, default='', help_text='Verified integrity evidence reference admitting this artifact (required for a portable mapping).', max_length=256),
        ),
        migrations.AddField(
            model_name='raesimagemapping',
            name='media_type',
            field=models.CharField(blank=True, default='', help_text='Portable ArtifactIdentity media type (for example application/vnd.raes.image).', max_length=256),
        ),
        migrations.AddField(
            model_name='raesimagemapping',
            name='provenance_ref',
            field=models.CharField(blank=True, default='', help_text='Verified provenance evidence reference admitting this artifact (required for a portable mapping).', max_length=256),
        ),
        migrations.AddConstraint(
            model_name='raesimagemapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact_digest', ''), ('artifact_id', ''), ('integrity_ref', ''), ('media_type', ''), ('provenance_ref', '')), models.Q(models.Q(('artifact_digest', ''), _negated=True), models.Q(('artifact_id', ''), _negated=True), models.Q(('media_type', ''), _negated=True), models.Q(('integrity_ref', ''), _negated=True), models.Q(('provenance_ref', ''), _negated=True)), _connector='OR'), name='raes_image_mapping_portable_identity_complete'),
        ),
    ]
