# Generated by Django 6.0.6 on 2026-07-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0051_raesimagemapping_artifact_digest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaesArtifactSatisfactionBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_address', models.CharField(help_text='Compiled RAES provisioning node address this binding realizes.', max_length=500)),
                ('requirement_id', models.CharField(help_text='Authored artifact requirement id this binding satisfies.', max_length=256)),
                ('artifact_id', models.CharField(help_text='Portable ArtifactIdentity id realized.', max_length=256)),
                ('artifact_version', models.CharField(help_text='Portable ArtifactIdentity version realized.', max_length=256)),
                ('digest', models.CharField(help_text="Portable ArtifactIdentity sha256 digest ('sha256:'+64 hex).", max_length=71)),
                ('media_type', models.CharField(help_text='Portable ArtifactIdentity media type.', max_length=256)),
                ('mechanism', models.CharField(help_text='Portable satisfaction mechanism (for example exact-artifact).', max_length=128)),
                ('acquisition', models.CharField(help_text='Acquisition transport of the selected route.', max_length=32)),
                ('timing', models.CharField(help_text='Realization timing of the selected route.', max_length=32)),
                ('image_ref', models.CharField(help_text='Concrete backend image the provisioner realizes.', max_length=500)),
                ('machine_type', models.CharField(blank=True, default='', max_length=100)),
                ('disk_size_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('disk_type', models.CharField(blank=True, default='', max_length=100)),
                ('binding_version', models.PositiveIntegerField(help_text='ArtifactBinding schema version (rolling-deploy seam).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('range', models.ForeignKey(help_text='Range this artifact-satisfaction decision is realized for.', on_delete=django.db.models.deletion.CASCADE, related_name='artifact_satisfaction_bindings', to='engine.range')),
            ],
            options={
                'db_table': 'engine_raes_artifact_satisfaction_binding',
                'constraints': [models.UniqueConstraint(fields=('range', 'target_address'), name='unique_raes_artifact_satisfaction_binding')],
            },
        ),
    ]
