# Generated by Django 6.0.6 on 2026-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0052_raesartifactsatisfactionbinding'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='raesimagemapping',
            name='raes_image_mapping_portable_identity_complete',
        ),
        migrations.AddField(
            model_name='raesimagemapping',
            name='artifact_version',
            field=models.CharField(blank=True, default='', help_text='Portable ArtifactIdentity version; part of the full identity a requirement is matched against.', max_length=256),
        ),
        migrations.AddConstraint(
            model_name='raesimagemapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact_digest', ''), ('artifact_id', ''), ('artifact_version', ''), ('integrity_ref', ''), ('media_type', ''), ('provenance_ref', '')), models.Q(models.Q(('artifact_digest', ''), _negated=True), models.Q(('artifact_id', ''), _negated=True), models.Q(('artifact_version', ''), _negated=True), models.Q(('media_type', ''), _negated=True), models.Q(('integrity_ref', ''), _negated=True), models.Q(('provenance_ref', ''), _negated=True)), _connector='OR'), name='raes_image_mapping_portable_identity_complete'),
        ),
    ]
