# Generated by Django 6.0.8 on 2026-08-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0053_remove_raesimagemapping_raes_image_mapping_portable_identity_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='placement_zone',
            field=models.CharField(blank=True, default='', help_text='GCE placement zone (#2029)', max_length=63),
        ),
    ]
