# Generated by Django 6.0.8 on 2026-09-04 03:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0055_range_egress_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarmRangeGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for cross-service correlation",
                        unique=True,
                    ),
                ),
                (
                    "bucket_id",
                    models.CharField(help_text="Warm-pool bucket id from the deployment policy", max_length=40),
                ),
                (
                    "compatibility_digest",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical sha256: compatibility digest (claim match key)",
                        max_length=80,
                    ),
                ),
                (
                    "effective_policy_fingerprint",
                    models.CharField(
                        help_text="sha256: fingerprint of the effective policy at provision time", max_length=80
                    ),
                ),
                ("backend", models.CharField(help_text="Admitted range backend bound at warm provision", max_length=8)),
                (
                    "range_source",
                    models.CharField(help_text="Range source this generation's bucket serves", max_length=32),
                ),
                (
                    "capacity_partition",
                    models.CharField(help_text="Declared capacity partition (ADR-047 catalog)", max_length=40),
                ),
                (
                    "capacity_scope_ref",
                    models.UUIDField(help_text="Pool capacity scope (Engine capacity ledger event_ref)"),
                ),
                (
                    "capacity_draw_key",
                    models.UUIDField(help_text="Idempotent capacity draw key for this generation", unique=True),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        db_index=True, help_text="System-owned request_id this generation is realized under"
                    ),
                ),
                (
                    "operation_id",
                    models.UUIDField(
                        blank=True, editable=False, help_text="Current operation generation fence", null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready (unclaimed)"),
                            ("claimed", "Claimed (activating)"),
                            ("activated", "Activated (consumed; owned by claimant)"),
                            ("unhealthy", "Unhealthy (quarantined)"),
                            ("retiring", "Retiring"),
                            ("terminal", "Terminal"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=16,
                    ),
                ),
                (
                    "claimed_by_request_id",
                    models.UUIDField(
                        blank=True, help_text="Launch request UUID that atomically claimed this generation", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, help_text="When the generation became READY (unclaimed)", null=True
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, help_text="When the generation was claimed", null=True),
                ),
                (
                    "idle_deadline",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Warm-idle expiry; a READY generation past this is retired",
                        null=True,
                    ),
                ),
                (
                    "retired_at",
                    models.DateTimeField(
                        blank=True, help_text="When destroy was confirmed (provider absence)", null=True
                    ),
                ),
                (
                    "range",
                    models.ForeignKey(
                        blank=True,
                        help_text="Realized system-owned Range (null until provisioned)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warm_generation",
                        to="engine.range",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["bucket_id", "state", "compatibility_digest"], name="warmgen_claim_idx"),
                    models.Index(fields=["state", "idle_deadline"], name="warmgen_reconcile_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("claimed_by_request_id__isnull", False)),
                        fields=("claimed_by_request_id",),
                        name="warmgen_one_claim_per_request",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("claimed_at__isnull", False),
                                ("claimed_by_request_id__isnull", False),
                                ("state", "claimed"),
                            ),
                            models.Q(
                                models.Q(("state", "claimed"), _negated=True), ("claimed_by_request_id__isnull", True)
                            ),
                            ("state__in", ["activated", "unhealthy", "retiring", "terminal"]),
                            _connector="OR",
                        ),
                        name="warmgen_claim_consistency",
                    ),
                ],
            },
        ),
    ]
