# Generated by Django 6.0.8 on 2026-09-12 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0056_warmrangegeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.UUIDField(db_index=True, help_text='Owning deployment; every lookup is deployment-scoped')),
                ('sharing_pool_id', models.CharField(help_text='Pool the allocation group belongs to', max_length=128)),
                ('routing_revision', models.PositiveIntegerField(help_text='Pool routing revision this group is pinned to')),
                ('affinity', models.CharField(help_text='per_user | per_pool', max_length=16)),
                ('owner_ref', models.CharField(blank=True, default='', help_text='Canonical owner for per_user; empty for per_pool', max_length=256)),
                ('allocation_group_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable allocation-group identity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'engine_sharing_allocation_group',
                'ordering': ['deployment_id', 'sharing_pool_id', 'routing_revision'],
                'constraints': [models.UniqueConstraint(fields=('deployment_id', 'sharing_pool_id', 'routing_revision', 'affinity', 'owner_ref'), name='engine_sharing_allocation_group_identity')],
            },
        ),
        migrations.CreateModel(
            name='MembershipProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.UUIDField(db_index=True, help_text='Owning deployment; every lookup is deployment-scoped')),
                ('sharing_binding_id', models.CharField(help_text='Binding whose selector this projection resolves', max_length=128)),
                ('selector_digest', models.CharField(default='', help_text='Digest of the selector this evidence resolves; a new selector version gets a distinct row', max_length=71)),
                ('membership_revision', models.PositiveIntegerField(help_text='Authoritative membership revision from the owning service')),
                ('fence_revision', models.PositiveIntegerField(default=0, help_text='Synchronously advanced invalidation fence')),
                ('state', models.CharField(default='unknown', help_text='allowed | revoked | unknown', max_length=16)),
                ('member_refs', models.JSONField(blank=True, default=list, help_text='Bounded canonical member references')),
                ('observed_at', models.DateTimeField(help_text='When the projection was observed from the owning service')),
                ('freshness_deadline', models.DateTimeField(help_text='Instant after which the projection is stale and denies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'engine_sharing_membership_projection',
                'ordering': ['deployment_id', 'sharing_binding_id'],
                'constraints': [models.UniqueConstraint(fields=('deployment_id', 'sharing_binding_id', 'selector_digest'), name='engine_sharing_membership_projection_identity')],
            },
        ),
        migrations.CreateModel(
            name='SharingPoolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.UUIDField(db_index=True, help_text='Owning deployment; every lookup is deployment-scoped')),
                ('sharing_pool_id', models.CharField(help_text='Stable logical pool identity within the deployment', max_length=128)),
                ('routing_revision', models.PositiveIntegerField(help_text='Current allocation-affinity/routing revision of the pool')),
                ('provider_pool_ref', models.CharField(blank=True, default='', help_text='Shared provider pool reference, if any', max_length=256)),
                ('capacity_account_ref', models.CharField(blank=True, default='', help_text='Shared capacity account reference, if any', max_length=256)),
                ('spend_account_refs', models.JSONField(blank=True, default=list, help_text='Distinct shared spend account references')),
                ('rate_account_refs', models.JSONField(blank=True, default=list, help_text='Distinct shared rate account references')),
                ('concurrency_account_refs', models.JSONField(blank=True, default=list, help_text='Distinct shared concurrency account references')),
                ('alias_affinities', models.JSONField(blank=True, default=list, help_text='Per-alias assignment affinity for the current routing revision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'engine_sharing_pool',
                'ordering': ['deployment_id', 'sharing_pool_id'],
                'constraints': [models.UniqueConstraint(fields=('deployment_id', 'sharing_pool_id'), name='engine_sharing_pool_identity')],
            },
        ),
        migrations.CreateModel(
            name='SharingBindingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.UUIDField(db_index=True, help_text='Owning deployment; every lookup is deployment-scoped')),
                ('sharing_binding_id', models.CharField(help_text='Stable logical binding identity within the deployment', max_length=128)),
                ('current_definition_revision', models.PositiveIntegerField(help_text='Latest published definition revision')),
                ('state', models.CharField(choices=[('active', 'active'), ('tombstoned', 'tombstoned')], default='active', help_text='active | tombstoned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(help_text='Pool this binding shares from; PROTECT keeps referenced pools from being deleted', on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='engine.sharingpoolrecord')),
            ],
            options={
                'db_table': 'engine_sharing_binding',
                'ordering': ['deployment_id', 'sharing_binding_id'],
            },
        ),
        migrations.CreateModel(
            name='SharingPoolRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_revision', models.PositiveIntegerField(help_text='Monotonic per-pool routing/affinity revision')),
                ('provider_pool_ref', models.CharField(blank=True, default='', help_text='Provider pool reference for this routing revision', max_length=256)),
                ('alias_affinities', models.JSONField(blank=True, default=list, help_text='Per-alias assignment affinity for this routing revision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(help_text='Pool this immutable routing revision belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='routing_revisions', to='engine.sharingpoolrecord')),
            ],
            options={
                'db_table': 'engine_sharing_pool_revision',
                'ordering': ['pool', '-routing_revision'],
            },
        ),
        migrations.CreateModel(
            name='SharingBindingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_revision', models.PositiveIntegerField(help_text='Monotonic per-binding definition revision')),
                ('definition_digest', models.CharField(help_text='sha256:<64hex> over the canonical published definition', max_length=71)),
                ('definition', models.JSONField(help_text='Canonical SharingBinding payload as published (references only, no secrets)')),
                ('catalog_digest', models.CharField(help_text='Catalog digest pinned at publication; resolution refuses a replacement catalog', max_length=71)),
                ('resolved_profile', models.JSONField(blank=True, default=None, help_text='ModelProfile resolved and frozen at publication, so resolution never re-reads a mutated catalog', null=True)),
                ('frozen_members', models.JSONField(blank=True, default=list, help_text='Resolved snapshot membership frozen at publication (empty for dynamic bindings)')),
                ('pool_routing_revision', models.PositiveIntegerField(help_text='Immutable pool routing revision this binding was validated against and resolves through')),
                ('selector_digest', models.CharField(help_text='Digest of the canonical selector; binds membership evidence to the exact published selector', max_length=71)),
                ('membership_mode', models.CharField(help_text='snapshot | dynamic', max_length=16)),
                ('priority', models.PositiveIntegerField(help_text='Operator-controlled precedence for non-combinable choices (0-1000)')),
                ('effective_from', models.DateTimeField(help_text="Start of the binding's effective interval")),
                ('effective_until', models.DateTimeField(help_text="End of the binding's effective interval")),
                ('observed_membership_revision', models.PositiveIntegerField(help_text='Membership revision observed at publication')),
                ('publisher_owner', models.CharField(help_text='Server-derived publisher owner namespace', max_length=128)),
                ('publisher_reference', models.CharField(help_text='Server-derived publisher reference (never trusted from the payload)', max_length=256)),
                ('empty_snapshot_ack', models.BooleanField(default=False, help_text='Operator acknowledged an empty resolved snapshot')),
                ('state', models.CharField(choices=[('active', 'active'), ('tombstoned', 'tombstoned')], default='active', help_text='active | tombstoned', max_length=16)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(help_text='Binding this immutable revision belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='engine.sharingbindingrecord')),
            ],
            options={
                'db_table': 'engine_sharing_binding_revision',
                'ordering': ['binding', '-definition_revision'],
                'constraints': [models.UniqueConstraint(fields=('binding', 'definition_revision'), name='engine_sharing_binding_revision_identity')],
            },
        ),
        migrations.AddConstraint(
            model_name='sharingbindingrecord',
            constraint=models.UniqueConstraint(fields=('deployment_id', 'sharing_binding_id'), name='engine_sharing_binding_identity'),
        ),
        migrations.AddConstraint(
            model_name='sharingpoolrevision',
            constraint=models.UniqueConstraint(fields=('pool', 'routing_revision'), name='engine_sharing_pool_revision_identity'),
        ),
    ]
