# Generated by Django 6.0.8 on 2026-09-13 02:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0057_model_access_sharing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreparationGrant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope_digest", models.CharField(db_index=True, max_length=71)),
                ("configuration_digest", models.CharField(max_length=71, unique=True)),
                ("configuration", models.JSONField()),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "permissions": [("manage_preparation_grants", "Manage artifact preparation cloud grants")],
            },
        ),
        migrations.CreateModel(
            name="PreparationAdapter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope_digest", models.CharField(max_length=71)),
                ("adapter_id", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=128)),
                ("manifest_digest", models.CharField(max_length=71)),
                ("manifest", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled"), ("retired", "Retired")],
                        default="enabled",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installed_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("grant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="engine.preparationgrant")),
            ],
            options={
                "permissions": [
                    ("manage_preparation_adapters", "Install and administer artifact preparation adapters"),
                    ("prepare_artifacts", "Request and inspect artifact preparation"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_digest", "adapter_id", "version"), name="prep_adapter_identity"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["enabled", "disabled", "retired"])), name="prep_adapter_state"
                    ),
                ],
            },
        ),
    ]
