# Generated by Django 6.0.8 on 2026-09-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0057_model_access_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharingbindingrevision",
            name="observed_assessment_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Complete automatic population assessed for the published membership revision",
            ),
        ),
        migrations.AddField(
            model_name="sharingbindingrevision",
            name="observed_authority_revisions",
            field=models.JSONField(
                default=list,
                help_text="Complete selector-authority fence revisions observed at publication",
            ),
        ),
        migrations.AddField(
            model_name="sharingbindingrevision",
            name="publisher_authority_revisions",
            field=models.JSONField(
                default=list,
                help_text="Complete publisher-authority fence revisions checked at publication",
            ),
        ),
        migrations.AddField(
            model_name="membershipprojection",
            name="assessment_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Complete automatic population assessed to produce this projection",
            ),
        ),
        migrations.AddField(
            model_name="membershipprojection",
            name="evidence_digest",
            field=models.CharField(
                default="sha256:0000000000000000000000000000000000000000000000000000000000000000",
                help_text="Digest of the complete canonical authority evidence for replay conflict detection",
                max_length=71,
            ),
        ),
        migrations.AddField(
            model_name="membershipprojection",
            name="publisher_authorities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="membershipprojection",
            name="selector_authorities",
            field=models.JSONField(
                default=list,
                help_text="Complete owner-qualified selector authority references and observed revisions",
            ),
        ),
        migrations.AddField(
            model_name="membershipprojection",
            name="spending_eligibilities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="membershipprojection",
            name="subject_authorizations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="membershipprojection",
            name="fence_revision",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Synchronous binding-local invalidation fence",
            ),
        ),
        migrations.AlterField(
            model_name="membershipprojection",
            name="member_refs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Bounded canonical complete owner-qualified member references",
            ),
        ),
        migrations.AlterField(
            model_name="membershipprojection",
            name="state",
            field=models.CharField(
                choices=[("allowed", "allowed"), ("revoked", "revoked"), ("unknown", "unknown")],
                default="unknown",
                help_text="allowed | revoked | unknown",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SharingAuthorityFence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deployment_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Owning deployment; every lookup is deployment-scoped",
                    ),
                ),
                ("authority_owner", models.CharField(max_length=128)),
                ("authority_reference", models.CharField(max_length=256)),
                ("authority_revision", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("allowed", "allowed"), ("revoked", "revoked"), ("unknown", "unknown")],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "engine_sharing_authority_fence",
                "ordering": ["deployment_id", "authority_owner", "authority_reference"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment_id", "authority_owner", "authority_reference"),
                        name="engine_sharing_authority_fence_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("authority_revision__gt", 0)),
                        name="engine_sharing_authority_fence_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ("allowed", "revoked", "unknown"))),
                        name="engine_sharing_authority_fence_state",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="membershipprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("allowed", "revoked", "unknown"))),
                name="engine_sharing_membership_projection_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(("membership_revision__gt", 0)),
                name="engine_sharing_membership_projection_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipprojection",
            constraint=models.CheckConstraint(
                condition=models.Q(("fence_revision__gt", 0)),
                name="engine_sharing_membership_projection_fence",
            ),
        ),
    ]
