# Generated by Django 6.0.8 on 2026-09-13 21:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0057_model_access_sharing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptVerifierRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("registration_revision", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("materialization_id", models.UUIDField(editable=False)),
                ("provisioning_operation_id", models.UUIDField(editable=False)),
                ("assignment_epoch", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("deployment_id", models.CharField(max_length=128)),
                ("profile_id", models.CharField(max_length=128)),
                ("provider_contract", models.CharField(max_length=128)),
                ("ctf_event_id", models.UUIDField()),
                ("ctf_participant_id", models.UUIDField()),
                (
                    "objectives",
                    models.JSONField(help_text="Bounded objective identifiers admitted for this assignment"),
                ),
                ("issuer_id", models.CharField(max_length=128)),
                ("provider_range_namespace", models.CharField(max_length=128)),
                ("provider_participant_namespace", models.CharField(max_length=128)),
                (
                    "key_mode",
                    models.CharField(
                        choices=[
                            ("remote_symmetric", "remote_symmetric"),
                            ("asymmetric_public", "asymmetric_public"),
                        ],
                        max_length=32,
                    ),
                ),
                ("algorithm_id", models.CharField(max_length=128)),
                ("key_id", models.CharField(max_length=128)),
                (
                    "secret_version_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider secret version reference; never projected to CTF",
                        max_length=500,
                    ),
                ),
                ("public_verification_key", models.TextField(blank=True, default="")),
                ("reset_generation", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(choices=[("active", "Active"), ("revoked", "Revoked")], default="active", max_length=16),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_verifier_registrations",
                        to="engine.range",
                    ),
                ),
            ],
            options={
                "db_table": "engine_receipt_verifier_registration",
                "ordering": ["range", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("range",),
                        name="engine_one_active_receipt_verifier_per_range",
                    ),
                    models.UniqueConstraint(
                        fields=("range", "assignment_epoch"),
                        name="engine_receipt_assignment_epoch_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("key_mode", "remote_symmetric"),
                                ("public_verification_key", ""),
                                models.Q(("secret_version_ref", ""), _negated=True),
                            ),
                            models.Q(
                                ("key_mode", "asymmetric_public"),
                                ("secret_version_ref", ""),
                                models.Q(("public_verification_key", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="engine_receipt_verifier_key_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("revoked_at__isnull", True), ("status", "active")),
                            models.Q(("revoked_at__isnull", False), ("status", "revoked")),
                            _connector="OR",
                        ),
                        name="engine_receipt_verifier_status_timestamp",
                    ),
                ],
            },
        ),
    ]
