# Generated by Django 6.0.8 on 2026-09-13 02:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0058_artifact_preparation_adapters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreparationOperation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope_digest", models.CharField(db_index=True, max_length=71)),
                ("input_digest", models.CharField(max_length=71, unique=True)),
                ("input", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("verifying", "Verifying"),
                            ("available", "Available"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("current_attempt_id", models.UUIDField(editable=False, null=True)),
                ("cleanup_pending", models.BooleanField(db_index=True, default=False)),
                ("failure_code", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adapter",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="engine.preparationadapter"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreparationAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("phase", models.CharField(max_length=16)),
                ("input", models.JSONField()),
                ("input_digest", models.CharField(max_length=71)),
                ("expires_at", models.DateTimeField()),
                ("dispatched_at", models.DateTimeField(null=True)),
                ("next_dispatch_at", models.DateTimeField()),
                ("dispatch_count", models.PositiveIntegerField(default=0)),
                ("lease_id", models.UUIDField(null=True)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("result", models.JSONField(null=True)),
                ("result_digest", models.CharField(blank=True, default="", max_length=71)),
                ("disposition", models.CharField(default="pending", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="engine.preparationoperation"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="preparationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["queued", "running", "verifying", "available", "failed", "cancelled"])
                ),
                name="prep_operation_state",
            ),
        ),
        migrations.AddIndex(
            model_name="preparationattempt",
            index=models.Index(fields=["disposition", "next_dispatch_at"], name="prep_attempt_dispatch"),
        ),
        migrations.AddConstraint(
            model_name="preparationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("phase__in", ["verify-inputs", "build", "verify-output", "cleanup"])),
                name="prep_attempt_phase",
            ),
        ),
    ]
