# Generated by Django 6.0.8 on 2026-09-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0060_preparation_scope_lock"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreparedArtifactAdmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_digest", models.CharField(db_index=True, max_length=71)),
                ("facts", models.JSONField()),
                ("facts_digest", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_mapping",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="engine.raesimagemapping"),
                ),
                (
                    "operation",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="engine.preparationoperation"),
                ),
            ],
        ),
    ]
