# Generated by Django 6.0.8 on 2026-09-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0061_prepared_artifact_admission"),
    ]

    operations = [
        migrations.AddField(
            model_name="raesartifactsatisfactionbinding",
            name="image_id",
            field=models.CharField(
                blank=True, default="", help_text="Verified immutable GCE image identity.", max_length=20
            ),
        ),
    ]
