# Generated by Django 6.0.8 on 2026-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0062_artifact_binding_image_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="preparationgrant",
            name="installation",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="preparationgrant",
            name="installation_digest",
            field=models.CharField(blank=True, max_length=71),
        ),
        migrations.AddField(
            model_name="preparationgrant",
            name="verified_at",
            field=models.DateTimeField(null=True),
        ),
    ]
