# Generated by Django 6.0.8 on 2026-09-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0058_receiptverifierregistration'),
        ('engine', '0064_raes_subnet_coordination'),
    ]

    operations = [
    ]
