# Generated by Django 6.0.8 on 2026-09-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0066_merge_sharing_authority_artifact_preparation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicOperationRetryBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deployment_scope", models.CharField(max_length=190)),
                ("actor_key", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("caller_key", models.CharField(max_length=200)),
                ("request_id", models.UUIDField(db_index=True, editable=False)),
                ("operation_id", models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ("intent_digest", models.CharField(max_length=71)),
                ("intent_projection_version", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("TOMBSTONE", "Tombstone")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "engine_public_operation_retry_binding",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment_scope", "actor_key", "action", "caller_key"),
                        name="uq_public_operation_retry_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RangeCleanupVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(db_index=True)),
                ("operation_id", models.UUIDField(db_index=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("VERIFIED_ABSENT", "Verified absent"),
                            ("RESIDUALS_FOUND", "Residuals found"),
                            ("INCOMPLETE", "Incomplete inventory"),
                        ],
                        max_length=24,
                    ),
                ),
                ("scope", models.JSONField()),
                ("residual_categories", models.JSONField(default=list)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "engine_range_cleanup_verification",
                "indexes": [models.Index(fields=["request_id", "created_at"], name="engine_cleanupver_req_idx")],
            },
        ),
    ]
