protocols = imap lmtp
mail_location = maildir:~/Maildir
listen = *
auth_mechanisms = plain login
passdb {
  driver = passwd-file
  args = /etc/dovecot/users
}
userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/%n
}
disable_plaintext_auth = no
ssl = no
