# Generated by Django 6.0 on 2025-12-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_control", "0003_update_os_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="chat_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="range",
            name="destroyed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="range",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="range",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="range",
            name="ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="range",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("ready", "Ready"),
                    ("paused", "Paused"),
                    ("resuming", "Resuming"),
                    ("destroying", "Destroying"),
                    ("destroyed", "Destroyed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="victim_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
