# Generated by Django 6.0 on 2025-12-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_control", "0006_create_provisioner_lambda_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
