# Generated by Django 6.0 on 2025-12-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mission_control", "0009_grant_kali_columns_to_provisioner"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="kali_ssh_key_secret_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secrets Manager ARN for Kali SSH private key",
                max_length=500,
            ),
        ),
        # Grant provisioner_lambda permission to update this column
        migrations.RunSQL(
            sql="""
                GRANT UPDATE (kali_ssh_key_secret_arn) ON mission_control_range TO provisioner_lambda;
            """,
            reverse_sql="""
                REVOKE UPDATE (kali_ssh_key_secret_arn) ON mission_control_range FROM provisioner_lambda;
            """,
        ),
    ]
