# Generated by Django - add victim_ssh_key_secret_arn field to Range model

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add victim_ssh_key_secret_arn field to Range model for Victim MCP access."""

    dependencies = [
        ("mission_control", "0011_create_mcp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="victim_ssh_key_secret_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secrets Manager ARN for Victim SSH private key",
                max_length=500,
            ),
        ),
    ]
