# Generated by Django 6.0 on 2025-12-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0011_create_mcp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cognito_sub",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cognito user pool subject identifier (UUID)",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="chat_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="range",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="range",
            name="kali_instance_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Kali EC2 instance ID (e.g., i-abc123)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="step_function_execution_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Step Functions execution ARN",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="subnet_cidr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subnet CIDR (e.g., 10.1.5.0/24)",
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="subnet_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AWS subnet ID (e.g., subnet-abc123)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="victim_instance_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="EC2 instance ID (e.g., i-abc123)",
                max_length=50,
            ),
        ),
        # Grant mcp_user SELECT on userprofile table for cognito_sub lookups
        migrations.RunSQL(
            sql="GRANT SELECT ON mission_control_userprofile TO mcp_user;",
            reverse_sql="REVOKE SELECT ON mission_control_userprofile FROM mcp_user;",
        ),
    ]
