# Generated by Django 6.0 on 2025-12-25 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0021_add_ngfw_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="ngfw_config",
            field=models.ForeignKey(
                blank=True,
                help_text="NGFW config to use for VM-Series bootstrap",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ranges",
                to="mission_control.ngfwconfig",
            ),
        ),
    ]
