# Generated by Django 6.0 on 2025-12-28 04:14

import mission_control.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0026_add_strata_config_to_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="range",
            name="ngfw_config",
        ),
        migrations.AlterField(
            model_name="strataconfig",
            name="scm_pin_value",
            field=mission_control.fields.EncryptedCharField(
                help_text="Auto-registration PIN value (encrypted at rest)",
                max_length=512,
            ),
        ),
        migrations.DeleteModel(
            name="NGFWConfig",
        ),
    ]
