// Issue #759 regression: prove that the SSM shell-command list
// generated by `buildNgfwSshCommands` actually preserves the
// SSH/PAN-OS exit code through cleanup when executed by /bin/sh.
//
// String-shape assertions in lib.test.js verify that the right
// pattern (set -e + EXIT trap) is emitted; this file pins the
// behavior the pattern is supposed to deliver: cleanup runs, the key
// file is removed, and the failing exit status survives.
//
// We replace the real `ssh` call by overriding PATH so that a stub
// `ssh` (which writes to a marker file and exits with a configured
// status) wins over the system one. `base64 -d` is a real binary on
// the SSM portal host; we reuse the system one here too.

/* eslint-disable security/detect-non-literal-fs-filename */
//
// All `fs.*Sync` paths in this file come from a freshly minted tmpdir,
// hardcoded `/tmp/ngfw-test-*` paths under our own control, or
// directly-constructed `path.join` calls — never user input. The
// eslint-plugin-security warnings here are false positives in the
// test context.

import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {
  writeFileSync,
  mkdtempSync,
  rmSync,
  chmodSync,
  existsSync,
  readFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { buildNgfwSshCommands } from "./lib.js";

let workDir;
let stubDir;
let shellAvailable = false;
let base64Available = false;

function probe(cmd, args) {
  const r = spawnSync(cmd, args, { encoding: "utf-8", timeout: 5000 });
  return !r.error && r.status === 0;
}

before(() => {
  workDir = mkdtempSync(path.join(tmpdir(), "ngfw-script-exec-"));
  stubDir = path.join(workDir, "stubs");
  // mkdir-equivalent: writeFileSync into a subpath needs the dir;
  // mkdtempSync already gave us workDir, so make stubDir explicitly.
  spawnSync("mkdir", ["-p", stubDir]);

  shellAvailable = probe("/bin/sh", ["-c", "true"]);
  base64Available = probe("base64", ["--version"]);
});

after(() => {
  if (workDir) rmSync(workDir, { recursive: true, force: true });
});

function writeSshStub(exitStatus, markerPath) {
  const stubPath = path.join(stubDir, "ssh");
  // The stub writes its argv to the marker so the test can confirm
  // it was invoked, then exits with the configured status. ssh's
  // stdin (the decoded PAN-OS command) is intentionally not consumed
  // — the test does not need to inspect it; lib.test.js already
  // asserts the base64 round-trip.
  writeFileSync(
    stubPath,
    `#!/bin/sh\necho "ssh stub invoked with: $*" > "${markerPath}"\nexit ${exitStatus}\n`
  );
  chmodSync(stubPath, 0o755);
  return stubPath;
}

function runScript(commands, env = {}) {
  // AWS-RunShellScript joins the commands list with newlines and runs
  // it as a single shell script; mirror that here.
  const script = commands.join("\n");
  return spawnSync("/bin/sh", ["-c", script], {
    encoding: "utf-8",
    timeout: 10000,
    env: { ...process.env, ...env },
  });
}

describe("buildNgfwSshCommands script execution (issue #759)", () => {
  const sshKey = "FAKE-TEST-KEY-MATERIAL\nopaque-bytes\nFAKE-TEST-KEY-END\n";
  const ngfwIp = "10.0.0.5";

  it("script exits 0 and removes the key file when ssh succeeds", (t) => {
    if (!shellAvailable || !base64Available) {
      t.skip("/bin/sh or base64 not available in this environment");
      return;
    }
    // The key path validator only allows /tmp/ngfw-... paths, so use a
    // /tmp value that is unique to this run.
    const realKeyPath = `/tmp/ngfw-test-success-${process.pid}.pem`;
    const markerPath = path.join(workDir, "marker-success.txt");
    writeSshStub(0, markerPath);

    const cmds = buildNgfwSshCommands({
      sshKey,
      ngfwIp,
      command: "show system info",
      keyPath: realKeyPath,
    });

    const result = runScript(cmds, { PATH: `${stubDir}:${process.env.PATH}` });

    try {
      assert.equal(result.status, 0, `stderr: ${result.stderr}`);
      // Cleanup ran: the key file no longer exists.
      assert.equal(existsSync(realKeyPath), false, "key file should be removed");
      // The ssh stub was actually invoked (proves the pipeline reached ssh).
      assert.ok(existsSync(markerPath), "ssh stub did not run");
      const marker = readFileSync(markerPath, "utf-8");
      assert.match(marker, /ssh stub invoked/);
      assert.ok(marker.includes(`-i ${realKeyPath}`), "marker missing key path");
    } finally {
      rmSync(realKeyPath, { force: true });
      rmSync(markerPath, { force: true });
    }
  });

  it("script propagates a non-zero ssh exit code through the EXIT trap and still cleans up", (t) => {
    if (!shellAvailable || !base64Available) {
      t.skip("/bin/sh or base64 not available in this environment");
      return;
    }
    const realKeyPath = `/tmp/ngfw-test-failure-${process.pid}.pem`;
    const markerPath = path.join(workDir, "marker-failure.txt");
    writeSshStub(42, markerPath);

    const cmds = buildNgfwSshCommands({
      sshKey,
      ngfwIp,
      command: "show system info",
      keyPath: realKeyPath,
    });

    const result = runScript(cmds, { PATH: `${stubDir}:${process.env.PATH}` });

    try {
      // Without the EXIT trap, the trailing rm would set the exit
      // code to 0 and SSM would report Success. The trap captures
      // $? before the rm and exits with the failing code, so SSM
      // sees the real PAN-OS / SSH failure.
      assert.equal(result.status, 42, `stderr: ${result.stderr}`);
      assert.equal(existsSync(realKeyPath), false, "key file should be removed even on failure");
      assert.ok(existsSync(markerPath), "ssh stub did not run");
    } finally {
      rmSync(realKeyPath, { force: true });
      rmSync(markerPath, { force: true });
    }
  });
});
