apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal
  namespace: shifter-platform
  annotations:
    iam.gke.io/gcp-service-account: placeholder-portal@placeholder-project.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workers
  namespace: shifter-platform
  annotations:
    iam.gke.io/gcp-service-account: placeholder-workers@placeholder-project.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: shifter-jobs
  annotations:
    iam.gke.io/gcp-service-account: placeholder-provisioner@placeholder-project.iam.gserviceaccount.com
