apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal
  namespace: shifter-platform
  annotations:
    iam.gke.io/gcp-service-account: shiftergcpdev-portal@shifter-gcp-dev.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workers
  namespace: shifter-platform
  annotations:
    iam.gke.io/gcp-service-account: shiftergcpdev-workers@shifter-gcp-dev.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: shifter-jobs
  annotations:
    iam.gke.io/gcp-service-account: shiftergcpdev-provisioner@shifter-gcp-dev.iam.gserviceaccount.com
