"""Tracked generated/sensitive artifact detection (ADR-004-R8).

Split out of ``secret_hygiene.py`` to keep each module under the file-length
limit; every public name here is re-imported by that module so the package
surface is unchanged.
"""
from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from .._common import (
    Violation,
    _repo_relative,
)
from ._secret_hygiene_git import _git_ls_files_stdout


# Centralized blocked-path / blocked-name set for the
# `no-tracked-generated-artifacts` check (ADR-004-R8). Each entry is a
# pair: (root prefix under which the rule applies, predicate over the
# repo-relative path's basename). The roots are intentionally narrow so
# unrelated source files with overlapping names elsewhere in the repo
# are not flagged.
#
# Terraform plan outputs: `tfplan`, `plan.out`, and any `*.tfplan` /
# `*.tfplan.binary` under the AWS or GCP terraform environment trees.
# These are generated security-sensitive artifacts; they may carry
# state-derived values, resource addresses, and provider metadata and
# must not be tracked in source.
#
# Bootstrap license/authcode material: `authcodes` (and `*.authcodes`)
# under `temp/bootstrap/`. These are pre-staging outputs from local
# bootstrap workflows and must not be committed.
#
# Polaris range build output: every tracked file under
# `scenario-dev/polaris/build/`. That tree is generated/runtime material and
# can carry challenge-local keys, tokens, database access files, and baked
# runtime payloads. Source inputs live outside `build/`.
#
# Polaris AWS operator run outputs: machine-readable provisioning state and
# human-readable status/health reports under `scripts/polaris-aws-range/`.
# These are regenerated by orchestrate_provisioning.py and
# check_range_health.py during live events and may contain participant or
# infrastructure identifiers.
_GENERATED_ARTIFACT_ROOTS: tuple[str, ...] = (
    "platform/terraform/environments/",
    "platform/terraform/gcp/environments/",
    "scenario-dev/polaris/build/",
    "scripts/polaris-aws-range/",
    "temp/bootstrap/",
)


def _is_terraform_plan_artifact(basename: str) -> bool:
    """Return True for Terraform plan output filenames.

    Matches the canonical names produced by `terraform plan -out=...`
    workflows: `tfplan` and `tfplan.binary` (binary plan files) and
    `plan.out` (typical text dump). Also matches the `*.tfplan` and
    `*.tfplan.binary` families so per-environment names like
    `dev.tfplan` and `prod.tfplan.binary` are caught. Case-sensitive
    to avoid over-matching unrelated source filenames such as
    `terraform_planner.py`.
    """
    if basename in ("tfplan", "tfplan.binary", "plan.out"):
        return True
    return basename.endswith((".tfplan", ".tfplan.binary"))


def _is_bootstrap_authcode_artifact(basename: str) -> bool:
    """Return True for tracked bootstrap license/authcode filenames."""
    return basename == "authcodes" or basename.endswith(".authcodes")


def _is_polaris_operator_run_artifact(basename: str) -> bool:
    """Return True for tracked Polaris AWS operator run outputs."""
    return basename in (
        "provisioning_state.json",
        "provisioning_status.md",
        "health_report.md",
        "postprovision_status.md",
    )


def _is_polaris_build_artifact(basename: str) -> bool:
    """Return True for any file under the Polaris build tree."""
    # The whole build/ tree is generated output, whatever the name.
    del basename
    return True


# Blocked-path prefix -> basename predicate. The prefixes are disjoint, so a
# repo-relative path is matched by at most one entry.
_GENERATED_ARTIFACT_PREDICATES: tuple[tuple[str, Callable[[str], bool]], ...] = (
    ("platform/terraform/", _is_terraform_plan_artifact),
    ("scenario-dev/polaris/build/", _is_polaris_build_artifact),
    ("scripts/polaris-aws-range/", _is_polaris_operator_run_artifact),
    ("temp/bootstrap/", _is_bootstrap_authcode_artifact),
)


def _generated_artifact_match(rel_path: str) -> bool:
    """Return True if a repo-relative path is a blocked generated artifact."""
    if not any(rel_path.startswith(root) for root in _GENERATED_ARTIFACT_ROOTS):
        return False
    basename = rel_path.rsplit("/", 1)[-1]
    return any(
        rel_path.startswith(prefix) and predicate(basename)
        for prefix, predicate in _GENERATED_ARTIFACT_PREDICATES
    )


def _iter_artifact_candidates(repo_root: Path) -> list[str]:
    """Return repo-relative paths of TRACKED files matching the policy.

    Codex review #1180 cycle 1 finding 1: the previous walk-the-
    filesystem implementation flagged any ignored local workspace
    file under the Terraform/temp roots, which would break
    `adr_guard --all --level ci` when a developer or earlier CI step
    generated an ephemeral `tfplan`. The contract is to block files
    that are tracked in source control (or staged for the next
    commit); files matched only by `.gitignore` are intentionally
    allowed. We delegate the source-controlled detection to
    `git ls-files`, which already considers both tracked + staged
    entries and is the canonical source for "what is in version
    control."

    A test that runs against a synthetic tmpdir (no `.git` present)
    falls back to the filesystem walk so the unit tests can build
    pseudo-trees without initializing a git repo. The fallback only
    triggers when there is no usable git index, never in real-repo
    use.
    """
    tracked = _git_tracked_under_roots(repo_root)
    if tracked is None:
        # No git index — synthetic test mode. Walk the filesystem.
        return _walk_filesystem_artifacts(repo_root)
    return [p for p in tracked if _generated_artifact_match(p)]


def _walk_filesystem_artifacts(repo_root: Path) -> list[str]:
    """Test-mode fallback: walk `_GENERATED_ARTIFACT_ROOTS` on disk
    and return matching repo-relative paths. Production code always
    reaches `_git_tracked_under_roots`; this branch is only exercised
    by unit tests building a synthetic tmpdir tree without a `.git`
    directory."""
    candidates: list[str] = []
    for root in _GENERATED_ARTIFACT_ROOTS:
        base = repo_root / root
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file():
                continue
            rel = _repo_relative(path, repo_root)
            if _generated_artifact_match(rel):
                candidates.append(rel)
    return candidates


def _git_tracked_under_roots(repo_root: Path) -> list[str] | None:
    """Return all tracked (and staged) repo-relative paths under
    `_GENERATED_ARTIFACT_ROOTS`, or `None` if `repo_root` is not a
    git working tree."""
    stdout = _git_ls_files_stdout(repo_root, _GENERATED_ARTIFACT_ROOTS)
    if stdout is None:
        return None
    output = stdout.decode("utf-8", errors="replace")
    return [entry for entry in output.split("\0") if entry]


def check_no_tracked_generated_artifacts(
    repo_root: Path, files: list[str] | None
) -> list[Violation]:
    """Forbid tracked generated/sensitive artifacts (ADR-004-R8).

    Three artifact families are blocked, each scoped narrowly:

    - Terraform plan outputs (`tfplan`, `plan.out`, `*.tfplan`,
      `*.tfplan.binary`) under `platform/terraform/environments/` and
      `platform/terraform/gcp/environments/`. Plan files are generated
      security-sensitive artifacts: they may carry state-derived
      values, resource addresses, provider metadata, and deployment-
      specific operational details.
    - License / authcode bootstrap material (`authcodes`,
      `*.authcodes`) under `temp/bootstrap/`. These pre-staging
      outputs must not be tracked.
    - Polaris range build output under `scenario-dev/polaris/build/`.
      This is generated/runtime material, not source.

    The check fails closed at the staged-source boundary. It does NOT
    parse plan binaries or echo file content — the violation message
    names the repo-relative path and the remediation.
    """
    violations: list[Violation] = []
    if files is not None:
        in_scope = sorted({p for p in files if _generated_artifact_match(p)})
    else:
        in_scope = sorted(set(_iter_artifact_candidates(repo_root)))
    for rel in in_scope:
        violations.append(
            Violation(
                check="no-tracked-generated-artifacts",
                rule_id="ADR-004-R8",
                path=rel,
                message=(
                    "Generated/sensitive artifact must not be tracked in source. "
                    "Remove with `git rm` and ensure the path is covered by "
                    ".gitignore + the ADR-004-R8 guardrail."
                ),
            )
        )
    return violations


__all__ = [
    "_GENERATED_ARTIFACT_PREDICATES",
    "_GENERATED_ARTIFACT_ROOTS",
    "_generated_artifact_match",
    "_git_tracked_under_roots",
    "_is_bootstrap_authcode_artifact",
    "_is_polaris_build_artifact",
    "_is_polaris_operator_run_artifact",
    "_is_terraform_plan_artifact",
    "_iter_artifact_candidates",
    "_walk_filesystem_artifacts",
    "check_no_tracked_generated_artifacts",
]
