"""Live cloud identifiers, terraform operational placeholders, mission-control flag literals."""
from __future__ import annotations

import ipaddress
import re
from pathlib import Path

from .._common import (
    Violation,
    _git_tracked_all,
    _read_text_safe,
    _repo_relative,
    _walk_all_files,
)


# ---------------------------------------------------------------------------
# ADR-004-R14: live cloud identifier hygiene.
#
# Strips reconnaissance-sensitive AWS infrastructure identifiers from tracked
# files and blocks their reintroduction. This is the low-entropy complement to
# gitleaks (which catches high-entropy secrets): account IDs, VPC/subnet IDs,
# and account- or UUID-suffixed S3 buckets are not secret, but they aid an
# attacker mapping a public-repo deployment's real infrastructure.
#
# Detection is by *pattern*, never by a denylist of real values - listing a
# real identifier here would re-commit the very thing the check removes. Real
# values that must stay committed (vendor connector templates whose account IDs
# must be exact; backend/state buckets read directly by `terraform init`) are
# retained via scoped `docs/adr/exceptions.yaml` entries (rule_id
# ADR-004-R14), applied centrally by `filter_excepted_violations`.
#
# Allowlist: a small fixed set of synthetic example account IDs. Placeholder
# and example forms (`vpc-xxxxxxxx`, `<your-account-id>`) are not matched at all
# because the real-identifier patterns require hex / 12 literal digits, which
# bracketed and `x`-filled placeholders cannot satisfy - so there is no
# universal `<...>` wildcard a real value could hide behind.
_IDENTIFIER_RULE_ID = "ADR-004-R14"
_IDENTIFIER_CHECK = "no-live-cloud-identifiers"

# 12-digit runs that are NOT reconnaissance-sensitive Shifter account IDs and
# are allowed to remain in tracked files:
#  - AWS documentation's canonical example account IDs + the all-zero
#    placeholder.
#  - Public AMI-publisher account IDs. These are well-known, documented AWS
#    accounts (Canonical, OffSec/Kali) used as `owner` filters to resolve
#    official base images; they are not Shifter infrastructure and changing
#    them would break AMI lookups.
_SYNTHETIC_ACCOUNT_IDS: frozenset[str] = frozenset(
    {
        # AWS docs canonical example account
        "123456789012",
        # AWS docs secondary example account
        "111122223333",
        # explicit all-zero placeholder
        "000000000000",
        # Canonical (Ubuntu) - public AMI publisher
        "099720109477",
        # OffSec (Kali Linux) - public AMI publisher
        "679593333241",
    }
)

# Generated / binary files that may carry incidental digit runs and never
# carry hand-authored operational identifiers. Skipped wholesale.
_IDENTIFIER_SKIP_SUFFIXES: tuple[str, ...] = (
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".svg", ".pdf", ".zip", ".tar",
    ".gz", ".tgz", ".bz2", ".xz", ".whl", ".woff", ".woff2", ".ttf", ".eot",
    ".mo", ".pyc", ".so", ".dylib", ".class", ".jar", ".wasm",
)
_IDENTIFIER_SKIP_BASENAMES: frozenset[str] = frozenset(
    {
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "Cargo.lock",
        ".terraform.lock.hcl",
    }
)
# Dependency lock files (uv.lock, requirements-*.lock, ...): autogenerated,
# carry pinned sha256 hashes whose decimal runs are not infrastructure IDs.
_IDENTIFIER_SKIP_SUFFIX_LOCK = ".lock"

# A real AWS account ID is exactly 12 decimal digits. The lookarounds suppress
# two false-positive shapes WITHOUT making `-` a universal account-ID boundary
# (which would miss reintroduction shapes like `account-<id>`, `aws-dev-<id>`,
# or a non-Shifter `bucket-<id>`):
#  - `(?<![0-9a-fA-F])` / `(?![0-9a-fA-F])`: not bordered by a hex char, so a
#    decimal run inside a longer hex hash is ignored.
#  - `(?<![0-9a-fA-F]{4}-)`: not the trailing 12-digit group of a UUID, whose
#    final group is preceded by `<4 hex>-` (e.g. `...-a716-446655440000`).
# A hyphen-prefixed account ID such as `account-<id>` is still caught because
# the chars before the digits (`ount-`) are not `<4 hex>-`.
_ACCOUNT_ID_RE = re.compile(
    r"(?<![0-9a-fA-F])(?<![0-9a-fA-F]{4}-)\d{12}(?![0-9a-fA-F])"
)
# VPC / subnet IDs are `vpc-` / `subnet-` followed by 8 (legacy) or 17 (long)
# hex chars. The hex requirement means `vpc-xxxxxxxx` placeholders never match.
_VPC_ID_RE = re.compile(r"\bvpc-[0-9a-f]{8}(?:[0-9a-f]{9})?\b")
_SUBNET_ID_RE = re.compile(r"\bsubnet-[0-9a-f]{8}(?:[0-9a-f]{9})?\b")
# Account-ID-suffixed Shifter bucket (reveals the account): `shifter-...-<12d>`.
_ACCT_BUCKET_RE = re.compile(r"\bshifter-[a-z0-9-]+-\d{12}\b")
# UUID-suffixed infra/state bucket: `shifter-[dev-]infra-<uuid>`. Retained for
# `terraform init` via a scoped path exception, flagged so the retention is
# explicit and auditable.
_UUID_BUCKET_RE = re.compile(
    r"\bshifter-[a-z0-9-]*infra-"
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b"
)

# Public IPv4 addresses in IaC (`.tf`/`.tfvars`/`.hcl`) are almost always an
# operator/participant allow-CIDR - i.e. someone's home/office IP, which is PII
# in a public repo. Flag any globally-routable IPv4 in IaC. Private (RFC1918),
# loopback, link-local, CGNAT, and documentation (RFC5737: 192.0.2 / 198.51.100
# / 203.0.113) ranges are `is_global == False` and are never flagged, so
# placeholders like `203.0.113.10/32` pass. A small allowlist covers well-known
# PUBLIC infrastructure constants that legitimately appear in IaC (Google /
# Cloudflare public DNS; GCP load-balancer health-check, IAP, and googleapis
# VIP ranges) and are not env-specific or sensitive. A genuinely required
# public IP is cleared with a scoped docs/adr/exceptions.yaml entry.
_IAC_IP_SUFFIXES: tuple[str, ...] = (".tf", ".tfvars", ".hcl")
_IPV4_RE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")

# The allowlist lives in a sibling data file so no globally-routable IP literal
# is embedded in this checker source (python:S1313).
_PUBLIC_IP_ALLOWLIST_PATH = (
    Path(__file__).resolve().parent / "cloud_identifiers_public_ip_allowlist.txt"
)


def _load_public_ip_allow_nets(path: Path) -> tuple[ipaddress.IPv4Network, ...]:
    """Load the well-known public-infrastructure IP allowlist from ``path``.

    Each line is a CIDR; blank lines and ``#`` comments (including trailing
    comments) are ignored.
    """
    nets: list[ipaddress.IPv4Network] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        entry = raw_line.split("#", 1)[0].strip()
        if entry:
            nets.append(ipaddress.ip_network(entry))
    return tuple(nets)


_PUBLIC_IP_ALLOW_NETS: tuple[ipaddress.IPv4Network, ...] = _load_public_ip_allow_nets(
    _PUBLIC_IP_ALLOWLIST_PATH
)


def _is_flaggable_public_ip(token: str) -> bool:
    """True for a globally-routable IPv4 that is not a well-known public infra
    constant - i.e. an operator/participant IP that should not be committed."""
    try:
        addr = ipaddress.ip_address(token)
    except ValueError:
        return False
    if not isinstance(addr, ipaddress.IPv4Address) or not addr.is_global:
        return False
    return not any(addr in net for net in _PUBLIC_IP_ALLOW_NETS)


def _scan_iac_public_ips(line: str) -> list[str]:
    """Return ["public IP address"] once when an IaC line carries a flaggable
    public IPv4 in its code (not in a `#` / `//` comment, where IPs are prose /
    policy examples), else []."""
    code = line.split("#", 1)[0].split("//", 1)[0]
    for token in _IPV4_RE.findall(code):
        if _is_flaggable_public_ip(token):
            return ["public IP address"]
    return []


def _identifier_skip(rel: str) -> bool:
    """True for paths that must not be scanned (binary / generated locks)."""
    basename = rel.rsplit("/", 1)[-1]
    if basename in _IDENTIFIER_SKIP_BASENAMES:
        return True
    if rel.endswith(_IDENTIFIER_SKIP_SUFFIX_LOCK):
        return True
    return rel.endswith(_IDENTIFIER_SKIP_SUFFIXES)


def _identifier_violation(rel: str, lineno: int, kind: str) -> Violation:
    """Build a violation that names the path, line, and identifier KIND only -
    never the live value (preflight error-surface rule)."""
    return Violation(
        check=_IDENTIFIER_CHECK,
        rule_id=_IDENTIFIER_RULE_ID,
        path=rel,
        message=(
            f"line {lineno}: live AWS {kind} in a tracked file (value redacted); "
            "move it to a deploy-time overlay/secret/env var or a placeholder, "
            "or add a scoped docs/adr/exceptions.yaml entry if it must stay"
        ),
    )


def _scan_identifier_line(line: str) -> list[str]:
    """Return the identifier KINDs found on a line. Bucket patterns are matched
    and masked first so the account-ID run they contain is not double-counted."""
    kinds: list[str] = []
    masked = line
    for rx, kind in ((_ACCT_BUCKET_RE, "account-suffixed S3 bucket name"),
                     (_UUID_BUCKET_RE, "infra/state S3 bucket name")):
        if rx.search(masked):
            kinds.append(kind)
            masked = rx.sub(lambda m: " " * len(m.group(0)), masked)
    for match in _ACCOUNT_ID_RE.finditer(masked):
        if match.group(0) not in _SYNTHETIC_ACCOUNT_IDS:
            kinds.append("account ID")
    if _VPC_ID_RE.search(masked):
        kinds.append("VPC id")
    if _SUBNET_ID_RE.search(masked):
        kinds.append("subnet id")
    return kinds


def _scan_identifier_file(path: Path, rel: str) -> list[Violation]:
    """Scan one tracked file for live cloud identifiers and IaC public IPs."""
    text = _read_text_safe(path)
    if text is None:
        return []
    is_iac = rel.endswith(_IAC_IP_SUFFIXES)
    violations: list[Violation] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        for kind in _scan_identifier_line(line):
            violations.append(_identifier_violation(rel, lineno, kind))
        if is_iac:
            for kind in _scan_iac_public_ips(line):
                violations.append(_identifier_violation(rel, lineno, kind))
    return violations


def _iter_identifier_candidates(repo_root: Path, files: list[str] | None) -> list[str]:
    """Repo-relative paths to scan: the given `files`, or every tracked file."""
    if files is not None:
        return list(files)
    tracked = _git_tracked_all(repo_root)
    if tracked is None:
        return _walk_all_files(repo_root)
    return tracked


def check_no_terraform_operational_placeholders(repo_root: Path, files: list[str] | None) -> list[Violation]:
    """Forbid operational placeholder strings in committed Terraform sources (ADR-004-R15).

    Scans tracked ``platform/terraform/**/*.tf`` files for known non-operational
    literals such as ``YOUR_EMAIL@example.com`` that must not ship in IaC. Real
    alert recipients and similar values belong in gitignored ``local.auto.tfvars``
    or deploy secrets, not hardcoded in ``.tf`` sources.
    """
    violations: list[Violation] = []
    placeholder_patterns = (
        re.compile(r"YOUR_EMAIL@example\.com", re.IGNORECASE),
        re.compile(r"subscriber_email_addresses\s*=\s*\[[^\]]*@example\.com", re.IGNORECASE),
    )
    for rel in _iter_identifier_candidates(repo_root, files):
        if not rel.startswith("platform/terraform/") or not rel.endswith(".tf"):
            continue
        path = repo_root / rel
        if not path.is_file():
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            for pattern in placeholder_patterns:
                if pattern.search(line):
                    violations.append(
                        Violation(
                            "no-terraform-operational-placeholders",
                            "ADR-004-R15",
                            rel,
                            f"Operational placeholder detected in Terraform source (line {lineno}). "
                            "Use a variable plus gitignored local.auto.tfvars or a deploy secret "
                            "instead of committing example.com alert recipients.",
                        )
                    )
                    break
    return violations


def check_no_live_cloud_identifiers(repo_root: Path, files: list[str] | None) -> list[Violation]:
    """Forbid live AWS infrastructure identifiers in tracked files (ADR-004-R14).

    Scans tracked files repo-wide (or the given `files`) for AWS account IDs,
    VPC/subnet IDs, and account- or UUID-suffixed Shifter S3 buckets. Detection
    is by pattern with a fixed synthetic-account allowlist; real values that
    must stay committed are cleared via scoped exceptions.yaml entries. Messages
    redact the matched value. Backstops gitleaks for low-entropy infrastructure
    identifiers it ignores.
    """
    violations: list[Violation] = []
    for rel in _iter_identifier_candidates(repo_root, files):
        if _identifier_skip(rel):
            continue
        path = repo_root / rel
        if not path.is_file():
            continue
        violations.extend(_scan_identifier_file(path, rel))
    return violations


# ---------------------------------------------------------------------------
# ADR-004-R16: no hardcoded CTF flag literals in Mission Control runtime code.
#
# The Mission Control walkthrough page is a thin handoff to the CTFd platform;
# challenge answers and flag content belong to the CTF/Polaris content domain
# (the native `ctf` app or the standalone CTFd sync path), never to Mission
# Control Python or templates. This check is the regression backstop for #560:
# it fails closed on answer-shaped `FLAG{...}` literals in MC runtime surfaces.
# CTF flags are low-entropy and are not caught by gitleaks; this is the
# complementary repo-specific rule, scoped by path so intentional flag content
# in tests, docs, the `ctf` app, and Polaris scenario sources is not touched.
#
# Detection is by pattern, never by a denylist of real values, and violation
# messages redact the matched value. Format-hint placeholders (`FLAG{...}`,
# `FLAG{<16-hex>}`, `FLAG{}`) are intentionally NOT flagged: they describe the
# answer shape rather than carrying one.
_MC_FLAG_RULE_ID = "ADR-004-R16"
_MC_FLAG_CHECK = "no-mission-control-flag-literals"

# Mission Control runtime roots. The mission_control package is all runtime -
# its tests live under shifter_platform/tests/mission_control/, outside these
# roots - and the template tree covers inline <script> JavaScript.
_MC_RUNTIME_ROOTS: tuple[str, ...] = (
    "shifter/shifter_platform/mission_control/",
    "shifter/shifter_platform/templates/mission_control/",
)
# Only hand-authored runtime text is scanned.
_MC_FLAG_SCAN_SUFFIXES: tuple[str, ...] = (".py", ".html", ".js", ".txt")

# An answer-shaped flag literal: `flag{...}` (case-insensitive) whose brace body
# is captured so the placeholder predicate below can reject format-hint shapes.
_MC_FLAG_RE = re.compile(r"(?i)\bflag\{([^}\n]*)\}")


def _mc_flag_is_placeholder(inner: str) -> bool:
    """True only for the explicit format-hint placeholder shapes documented in
    ADR-004-R16: an empty body (``FLAG{}``), the ellipsis form (``FLAG{...}``),
    and a single angle-bracket template token (``FLAG{<16-hex>}``).

    The match is deliberately narrow so the guard fails closed: a body that
    merely *contains* a dot, an angle bracket, or other punctuation alongside
    real answer text (for example ``FLAG{my<answer>}`` or ``FLAG{real.answer.42}``)
    is a concrete answer, not a placeholder, and is flagged."""
    stripped = inner.strip()
    if not stripped:  # FLAG{}
        return True
    # ellipsis form FLAG{...}
    if set(stripped) == {"."}:
        return True
    # One <...> template token and nothing else (FLAG{<16-hex>}). An answer
    # with any text outside the brackets does not match, so it stays flagged.
    return re.fullmatch(r"<[^<>]*>", stripped) is not None


def _is_mc_runtime_path(rel: str) -> bool:
    """True for a Mission Control runtime file the flag check should scan."""
    return (
        rel.startswith(_MC_RUNTIME_ROOTS)
        and rel.endswith(_MC_FLAG_SCAN_SUFFIXES)
        and "/__pycache__/" not in rel
    )


def _mc_flag_violation(rel: str, lineno: int) -> Violation:
    """Build a violation that names path + line only - never the flag value
    (preflight error-surface rule)."""
    return Violation(
        check=_MC_FLAG_CHECK,
        rule_id=_MC_FLAG_RULE_ID,
        path=rel,
        message=(
            f"line {lineno}: hardcoded CTF flag literal in Mission Control "
            "runtime code (value redacted); move challenge content to the "
            "CTF/CTFd content domain instead of shipping it in the app path"
        ),
    )


def _scan_mc_flag_file(path: Path, rel: str) -> list[Violation]:
    """Scan one Mission Control runtime file for answer-shaped flag literals."""
    text = _read_text_safe(path)
    if text is None:
        return []
    violations: list[Violation] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        for match in _MC_FLAG_RE.finditer(line):
            if not _mc_flag_is_placeholder(match.group(1)):
                violations.append(_mc_flag_violation(rel, lineno))
    return violations


def _iter_mc_flag_candidates(repo_root: Path, files: list[str] | None) -> list[str]:
    """Mission Control runtime paths to scan: from `files`, or by walking the roots."""
    if files is not None:
        return [rel for rel in files if _is_mc_runtime_path(rel)]
    candidates: list[str] = []
    for root in _MC_RUNTIME_ROOTS:
        base = repo_root / root
        if not base.is_dir():
            continue
        for path in base.rglob("*"):
            if not path.is_file():
                continue
            rel = _repo_relative(path, repo_root)
            if _is_mc_runtime_path(rel):
                candidates.append(rel)
    return candidates


def check_mission_control_no_flag_literals(repo_root: Path, files: list[str] | None) -> list[Violation]:
    """Forbid hardcoded CTF flag literals in Mission Control runtime code (ADR-004-R16).

    Scans the mission_control package and the mission_control template tree for
    answer-shaped ``FLAG{...}`` literals, skipping format-hint placeholders. The
    path scope intentionally excludes tests, docs, the native ``ctf`` app, and
    Polaris scenario sources, where flag content is legitimate. Detection is by
    pattern and messages redact the matched value. Backstops gitleaks for
    low-entropy CTF flags it ignores.
    """
    violations: list[Violation] = []
    for rel in _iter_mc_flag_candidates(repo_root, files):
        path = repo_root / rel
        if not path.is_file():
            continue
        violations.extend(_scan_mc_flag_file(path, rel))
    return violations
