# Generated by Django 6.0 on 2026-01-01 08:49

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User-friendly name", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this credential expires (user sets at creation)",
                        null=True,
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time credential was validated against external system",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time credential was used for provisioning",
                        null=True,
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("scm", "SCM Registration"),
                            ("deployment_profile", "NGFW Deployment Profile"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "scm_folder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "scm_pin_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "scm_pin_value",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "sls_region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("americas", "Americas"),
                            ("europe", "Europe"),
                            ("japan", "Japan"),
                            ("asiapacific", "Asia Pacific"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "authcode",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credential",
                "verbose_name_plural": "Credentials",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("user", "name"),
                        name="unique_active_credential_name_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("credential_type", "deployment_profile"),
                            ("deleted_at__isnull", True),
                        ),
                        fields=("user", "authcode"),
                        name="unique_active_authcode_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("credential_type", "scm"), ("deleted_at__isnull", True)
                        ),
                        fields=("user", "scm_folder_name", "scm_pin_id"),
                        name="unique_active_scm_folder_pin_per_user",
                    ),
                ],
            },
        ),
    ]
