# Generated by Django 6.0 on 2026-01-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_migrate_credentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="RangeInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_id", models.IntegerField(unique=True)),
                ("scenario_id", models.CharField(max_length=50)),
                ("user_id", models.IntegerField()),
                ("agent_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Range Instance",
                "verbose_name_plural": "Range Instances",
            },
        ),
    ]
