# Generated by Django 6.0 on 2026-01-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_add_range_instance"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "extensions",
                    models.JSONField(
                        default=list,
                        help_text="File extensions that map to this OS (e.g., ['.msi'])",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating System",
                "verbose_name_plural": "Operating Systems",
                "ordering": ["name"],
            },
        ),
    ]
