# Generated by Django 6.0 on 2026-01-01 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_seed_operating_systems"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User-friendly name", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("s3_key", models.CharField(help_text="S3 object key", max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size_bytes", models.PositiveBigIntegerField()),
                ("sha256_hash", models.CharField(max_length=64)),
                (
                    "os",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cms_agents",
                        to="cms.operatingsystem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Config",
                "verbose_name_plural": "Agent Configs",
                "ordering": ["-created_at"],
            },
        ),
    ]
