# Generated by Django 6.0 on 2026-01-01 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_add_agentconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rangeinstance",
            name="agent_id",
        ),
        migrations.AddField(
            model_name="rangeinstance",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="range_instances",
                to="cms.agentconfig",
            ),
        ),
    ]
