# Generated by Django 6.0 on 2026-01-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_add_userngfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rangeinstance",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
