# Generated by Django 6.0 on 2026-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_add_status_deleted_at_to_rangeinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="range_spec",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
