# Generated by Django 6.0 on 2026-01-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_add_range_spec_to_rangeinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentconfig",
            name="sha256_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
