# Generated by Django 6.0 on 2026-01-07 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0011_make_sha256_hash_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spec_class",
                    models.CharField(
                        help_text="Dotted path to Pydantic spec class (e.g., 'shared.schemas.SCMCredentialSpec')",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credential Type",
                "verbose_name_plural": "Credential Types",
            },
        ),
        migrations.RemoveConstraint(
            model_name="credential",
            name="unique_active_authcode_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="credential",
            name="unique_active_scm_folder_pin_per_user",
        ),
        migrations.AddField(
            model_name="credential",
            name="data",
            field=models.JSONField(
                default=dict,
                help_text="Type-specific credential data (validated by spec_class)",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="credential_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credentials",
                to="cms.credentialtype",
            ),
        ),
        migrations.RemoveField(
            model_name="credential",
            name="authcode",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="last_used_at",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="last_verified_at",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="scm_folder_name",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="scm_pin_id",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="scm_pin_value",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="sls_region",
        ),
    ]
