# Generated by Django 6.0 on 2026-01-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_add_instance_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spec_class",
                    models.CharField(
                        help_text="Dotted path to Pydantic spec class", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "App Type",
                "verbose_name_plural": "App Types",
            },
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User-friendly name", max_length=100),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Type-specific app data (validated by spec_class)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "app_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apps",
                        to="cms.apptype",
                    ),
                ),
            ],
            options={
                "verbose_name": "App",
                "verbose_name_plural": "Apps",
                "ordering": ["-created_at"],
            },
        ),
    ]
