# Generated by Django 6.0 on 2026-01-10 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0018_seed_credential_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(help_text="Subnet name", max_length=100)),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="SubnetSpec data (instances, connected_to)",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnets",
                        to="cms.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet",
                "verbose_name_plural": "Subnets",
                "ordering": ["-created_at"],
            },
        ),
    ]
