# Generated by Django 6.0 on 2026-01-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0019_add_subnet_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="request",
            field=models.ForeignKey(
                blank=True,
                help_text="CMS Request that spawned this range (new pattern)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="range_instances",
                to="cms.request",
            ),
        ),
        migrations.AlterField(
            model_name="rangeinstance",
            name="range_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="request_type",
            field=models.CharField(
                choices=[("range", "RANGE"), ("ngfw", "NGFW")],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
