# Generated by Django 6.0.4 on 2026-05-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_add_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialtype',
            name='spec_class',
            field=models.CharField(help_text='Dotted path to Pydantic spec class', max_length=255),
        ),
    ]
