# Generated by Django 6.0.4 on 2026-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_alter_credentialtype_spec_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Last time credential was used for provisioning', null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, help_text='Last time credential was validated against external system', null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this credential expires (user sets at creation)', null=True),
        ),
    ]
