# Generated by Django 6.0.4 on 2026-05-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_alter_rangeinstance_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentconfig',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Agent Config', 'verbose_name_plural': 'Agent Configs'},
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Instance', 'verbose_name_plural': 'Instances'},
        ),
        migrations.AlterModelOptions(
            name='subnet',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Subnet', 'verbose_name_plural': 'Subnets'},
        ),
    ]
