# Generated by Django 6.0.4 on 2026-05-11

from __future__ import annotations

from typing import Any

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.db import migrations

SENSITIVE_CREDENTIAL_DATA_KEYS = frozenset({"authcode", "scm_pin_value"})
ENCRYPTED_VALUE_PREFIX = "enc:v1:"


def encrypt_existing_credential_data(apps, schema_editor):
    transform_existing_credential_data(apps, encrypt=True)


def decrypt_existing_credential_data(apps, schema_editor):
    transform_existing_credential_data(apps, encrypt=False)


def transform_existing_credential_data(apps, *, encrypt: bool):
    Credential = apps.get_model("cms", "Credential")
    credentials_to_update = []

    for credential in Credential.objects.all().iterator(chunk_size=1000):
        data = credential.data
        if not isinstance(data, dict):
            continue

        transformed = transform_sensitive_credential_data(data, encrypt=encrypt)
        if transformed != data:
            credential.data = transformed
            credentials_to_update.append(credential)

    if credentials_to_update:
        Credential.objects.bulk_update(credentials_to_update, ["data"])


def transform_sensitive_credential_data(data: dict[str, Any], *, encrypt: bool) -> dict[str, Any]:
    transformed = data.copy()
    for key in SENSITIVE_CREDENTIAL_DATA_KEYS:
        value = transformed.get(key)
        if not isinstance(value, str) or value == "":
            continue
        transformed[key] = encrypt_value(value) if encrypt else decrypt_value(value)
    return transformed


def encrypt_value(value: str) -> str:
    if value.startswith(ENCRYPTED_VALUE_PREFIX):
        return value
    encrypted = fernet().encrypt(value.encode("utf-8")).decode("utf-8")
    return f"{ENCRYPTED_VALUE_PREFIX}{encrypted}"


def decrypt_value(value: str) -> str:
    if not value.startswith(ENCRYPTED_VALUE_PREFIX):
        return value
    token = value.removeprefix(ENCRYPTED_VALUE_PREFIX)
    try:
        return fernet().decrypt(token.encode("utf-8")).decode("utf-8")
    except InvalidToken as exc:
        raise ValueError("Credential data contains an invalid encrypted value") from exc


def fernet() -> Fernet:
    return Fernet(settings.FIELD_ENCRYPTION_KEY.encode("utf-8"))


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0027_alter_agentconfig_options_alter_app_options_and_more"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_credential_data, decrypt_existing_credential_data),
    ]
