# Generated by Django 6.0.4 on 2026-05-03 15:59

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_alter_agentconfig_options_alter_app_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentconfig',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Agent Config', 'verbose_name_plural': 'Agent Configs'},
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Instance', 'verbose_name_plural': 'Instances'},
        ),
        migrations.AlterModelOptions(
            name='rangeinstance',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'verbose_name': 'Range Instance', 'verbose_name_plural': 'Range Instances'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'Scenario', 'verbose_name_plural': 'Scenarios'},
        ),
        migrations.AlterModelOptions(
            name='subnet',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Subnet', 'verbose_name_plural': 'Subnets'},
        ),
        migrations.AlterModelManagers(
            name='agentconfig',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='app',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='credential',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='instance',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rangeinstance',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='request',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='scenario',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subnet',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
