# Generated by Django 6.0.6 on 2026-06-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_spec_slug_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
