# Generated by Django 6.0.6 on 2026-06-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0031_rangeinstance_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="range_source",
            field=models.CharField(
                choices=[("mission_control", "MISSION_CONTROL"), ("ctf", "CTF")],
                default="mission_control",
                help_text="Server-derived provenance: which product path created this range.",
                max_length=20,
            ),
        ),
    ]
