# Generated by Django 6.0.6 on 2026-07-03 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_remove_legacy_experiments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcesPackageSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_id', models.SlugField(help_text='Catalog id for this ACES package-source entry', max_length=100, unique=True)),
                ('source_kind', models.CharField(choices=[('repo', 'Repository-managed'), ('object', 'Object storage')], default='repo', help_text='Where the package is resolved from (repo-managed or object storage)', max_length=16)),
                ('contract_kind', models.CharField(help_text="Package contract discriminator (e.g. 'aces')", max_length=32)),
                ('contract_profile', models.CharField(help_text="Contract profile the package claims (e.g. 'shifter')", max_length=128)),
                ('package_ref', models.CharField(help_text='Repo-relative path or object-storage key for the package root', max_length=512)),
                ('package_version', models.CharField(help_text='Immutable package version or ref', max_length=128)),
                ('package_digest', models.CharField(help_text="Package content digest ('sha256:<64 hex>')", max_length=71)),
                ('lock_ref', models.CharField(blank=True, default='', help_text='Repo-relative path or object-storage key for the lock artifact', max_length=512)),
                ('lock_digest', models.CharField(blank=True, default='', help_text="Lock artifact digest ('sha256:<64 hex>')", max_length=71)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Bounded provenance references (repo/commit/tool/report); no secrets or bodies')),
                ('conformance_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', help_text='Conformance readiness for the claimed profile', max_length=16)),
                ('conformance_report_ref', models.CharField(blank=True, default='', help_text='Reference to a conformance report (not its contents)', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ACES Package Source',
                'verbose_name_plural': 'ACES Package Sources',
                'ordering': ['scenario_id'],
            },
        ),
    ]
