# Generated by Django 6.0.6 on 2026-07-12 23:48

from django.db import migrations, models
from django.db.models import Count


def _forbid_existing_active_duplicates(apps, schema_editor):
    """Refuse to add the constraint while active-range duplicates already exist.

    Read-only guard (no deletes, no status edits): a partial unique index
    cannot be created on a table that already violates it, and #307's design
    requires existing duplicates to be deprovisioned through the real range
    lifecycle (cloud teardown) first -- never hard-deleted or status-hacked by
    a migration. This surfaces the offending (user_id, range_source) groups so
    the operator prerequisite is actionable instead of an opaque index error.

    "Active" mirrors ``cms.services.get_active_range``: a non-soft-deleted row
    whose status is not ``destroying``.
    """
    RangeInstance = apps.get_model("cms", "RangeInstance")
    offending = list(
        RangeInstance.objects.filter(deleted_at__isnull=True)
        .exclude(status="destroying")
        .values("user_id", "range_source")
        .annotate(active_count=Count("pk"))
        .filter(active_count__gt=1)
        .order_by("user_id", "range_source")
    )
    if offending:
        groups = ", ".join(
            f"(user_id={row['user_id']}, range_source={row['range_source']}, count={row['active_count']})"
            for row in offending
        )
        raise RuntimeError(
            "Cannot add the one-active-range-per-source constraint: "
            f"{len(offending)} (user_id, range_source) group(s) already hold multiple active ranges: "
            f"{groups}. Deprovision the duplicate active ranges through the normal range lifecycle "
            "(cloud teardown) before applying this migration; do not delete or status-edit the rows "
            "directly."
        )


def _noop_reverse(apps, schema_editor):
    """No-op reverse: the guard makes no schema or data change to undo."""


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0035_add_aces_package_source"),
    ]

    operations = [
        migrations.RunPython(_forbid_existing_active_duplicates, _noop_reverse),
        migrations.AddConstraint(
            model_name="rangeinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("status", "destroying"), _negated=True)),
                fields=("user_id", "range_source"),
                name="uq_rangeinstance_active_per_user_source",
            ),
        ),
    ]
