# Generated by Django 6.0.6 on 2026-07-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_rangeinstance_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeinstance',
            name='workspace_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Workspace this range is scoped to (soft reference; see ADR-046).', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='workspace_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Workspace this request was launched in (soft reference; see ADR-046).', null=True),
        ),
    ]
