# Generated by Django 6.0.8 on 2026-08-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_raes_hard_cutover'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scenario',
            name='unique_active_scenario_id',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
        migrations.AlterField(
            model_name='scenariometadata',
            name='scenario_id',
            field=models.CharField(
                help_text='Stable RAES package-source scenario ID',
                max_length=100,
                unique=True,
            ),
        ),
    ]
