# Generated by Django 6.0.8 on 2026-09-13 02:33
"""Add RangeInstance.extension_days generation snapshot + backfill (issue #27).

The extension increment becomes a per-generation snapshot so a later deployment
lease-policy change never rewrites an existing generation's increment. Existing
Mission Control generations launched under the historical fixed policy, so they
are backfilled with the historical 30-day increment. Deterministic: it uses the
historical constant and never reads current settings, so re-running against any
tree yields the same result.
"""

from django.db import migrations, models

# Historical Mission Control extension increment prior to configurable leases (#27).
_HISTORICAL_MISSION_CONTROL_EXTENSION_DAYS = 30


def backfill_mission_control_increment(apps, schema_editor):
    RangeInstance = apps.get_model("cms", "RangeInstance")
    # A leased Mission Control generation has ``expires_at`` set (mirrors the lease
    # bounds added by migration 0037). Record its historical increment without
    # touching either persisted deadline. CTF and legacy unleased rows never use the
    # Mission Control extension path, so they keep a null increment.
    RangeInstance.objects.filter(
        range_source="mission_control",
        expires_at__isnull=False,
        extension_days__isnull=True,
    ).update(extension_days=_HISTORICAL_MISSION_CONTROL_EXTENSION_DAYS)


def noop_reverse(apps, schema_editor):
    # Reversing the AddField drops the column; no data reversal is required.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0043_backfill_workspace_quota_reservations"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinstance",
            name="extension_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Extension increment (days) snapshotted from the deployment lease policy when this generation's user lease was first assigned. A later policy change never rewrites it, so each generation keeps the increment it launched with (issue #27).",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_mission_control_increment, noop_reverse),
    ]
