# Generated by Django 6.0.8 on 2026-09-14 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_mission_control_runtime_lease_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioModelNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.SlugField(help_text='Catalog id of the RAES package these model needs bind to', max_length=100, unique=True)),
                ('authored_package_digest', models.CharField(help_text="Pack content digest the needs were authored against ('sha256:<64 hex>')", max_length=71)),
                ('needs', models.JSONField(help_text='Map of workload_role to a shared.model_access.ScenarioNeed payload')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenario Model Needs',
                'verbose_name_plural': 'Scenario Model Needs',
                'ordering': ['scenario_id'],
            },
        ),
    ]
