id: cortex_deployment_experience
name: Cortex Deployment Experience
description: A range designed for use in the Cortex Deployment Experience. Includes a domain controller, two workstations, a server, and an attacker.
enabled: true
ngfw: true

instances:
  - name: Attacker
    role: attacker
    os_type: kali
    xdr_agent: false
    join_domain: false
    ai_agent: true

  - name: Domain Controller
    role: dc
    os_type: windows
    domain_controller: true
    xdr_agent: false
    ai_agent: true
    dc_config:
      domain_name: internal.shifter
      netbios_name: INTSHIFTER

  - name: Cortex Host
    role: victim
    os_type: ubuntu
    xdr_agent: false
    join_domain: true
    ai_agent: true

  - name: Workstation 1
    role: victim
    os_type: windows
    xdr_agent: false
    join_domain: true
    ai_agent: true

  - name: Workstation 2
    role: victim
    os_type: windows
    xdr_agent: false
    join_domain: true
    ai_agent: true

  - name: Server
    role: victim
    os_type: ubuntu
    xdr_agent: false
    join_domain: true
    ai_agent: true

subnets:
  - name: dc_network
    instances: [Domain Controller, Cortex Host]
    connected_to: [workstation_network, server_network, attacker_network]

  - name: workstation_network
    instances: [Workstation 1, Workstation 2]
    connected_to: [dc_network, server_network, attacker_network]

  - name: server_network
    instances: [Server]
    connected_to: [dc_network, workstation_network, attacker_network]

  - name: attacker_network
    instances: [Attacker]
    connected_to: [dc_network, workstation_network, server_network]
