# Generated by Django 6.0 on 2025-12-14 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-friendly name for this key", max_length=100
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="Key prefix for identification",
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash of full key", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("risk", "Risk"),
                            ("comment", "Comment"),
                            ("apikey", "API Key"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("restore", "Restore"),
                            ("close", "Close"),
                            ("reopen", "Reopen"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("user", "User"), ("apikey", "API Key")], max_length=10
                    ),
                ),
                ("actor_id", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("previous_state", models.JSONField(blank=True, null=True)),
                ("new_state", models.JSONField(blank=True, null=True)),
                (
                    "context",
                    models.TextField(blank=True, help_text="Optional reason or notes"),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="risk_regist_entity__6c222c_idx",
                    ),
                    models.Index(
                        fields=["actor_type", "actor_id"],
                        name="risk_regist_actor_t_bb75e4_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="risk_regist_timesta_a16e88_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("mitigating", "Mitigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "stride_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of STRIDE category codes (S, T, R, I, D, E)",
                    ),
                ),
                (
                    "likelihood_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-5 scale", null=True
                    ),
                ),
                (
                    "impact_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-5 scale", null=True
                    ),
                ),
                ("attack_vector", models.TextField(blank=True)),
                ("affected_assets", models.TextField(blank=True)),
                ("mitigation_status", models.TextField(blank=True)),
                ("resolution_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "deleted_at"],
                        name="risk_regist_status_72418c_idx",
                    ),
                    models.Index(
                        fields=["severity", "deleted_at"],
                        name="risk_regist_severit_8a84c9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="risk_regist_created_db308e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author_apikey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="risk_register.apikey",
                    ),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="risk_register.comment",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="risk_register.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["prefix"], name="risk_regist_prefix_e112e0_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["created_by", "revoked_at"],
                name="risk_regist_created_63595a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["risk", "deleted_at", "created_at"],
                name="risk_regist_risk_id_894477_idx",
            ),
        ),
    ]
