"""Sanitized concurrency-envelope report renderer.

Renders the evidence artifact the issue's acceptance criteria call for: target
environment, deployment shape, per-route tail latency and error distribution,
websocket close-code accounting, same-window provider metrics (or named gaps),
first-mover attribution, and a supported-concurrency conclusion with margin and
limiting factor feeding #910.

The renderer only receives sanitized aggregates (the stats summary holds no raw
bodies, the metrics result holds named signals). A final sanitization scan is
defense in depth: if a caller-supplied free-text field smuggled a secret, the
renderer refuses to write it rather than committing a leaky report.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

# Patterns that must never appear in a committed report. Conservative on purpose.
_SECRET_PATTERNS = [
    re.compile(r"sessionid\s*=", re.IGNORECASE),
    re.compile(r"csrftoken\s*=", re.IGNORECASE),
    re.compile(r"authorization\s*:", re.IGNORECASE),
    re.compile(r"\bpassword\s*[=:]", re.IGNORECASE),
    re.compile(r"\b(secret|token)\s*[=:]\s*\S", re.IGNORECASE),
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),  # AWS access key id
]


class ReportError(Exception):
    """Raised when the report cannot be rendered safely (e.g. would leak a secret)."""


@dataclass(frozen=True)
class RunMeta:
    started_at: str
    ended_at: str
    git_sha: str | None = None
    image_digest: str | None = None


@dataclass(frozen=True)
class DeploymentShape:
    instances: str | None = None
    process_model: str | None = None
    terminal_caps: str | None = None
    redis_posture: str | None = None
    rds_posture: str | None = None
    guacamole_posture: str | None = None


@dataclass(frozen=True)
class Conclusion:
    supported_concurrency: str
    margin: str
    limiting_factor: str
    sizing_implication: str
    first_mover_signal: str


def _u(value: str | None) -> str:
    """Render an unknown field explicitly rather than blank or guessed."""
    return value if value else "unknown"


def _fmt_latency(latency: dict[str, Any]) -> str:
    def cell(key: str) -> str:
        v = latency.get(key)
        return f"{v:.1f}" if isinstance(v, (int, float)) else "n/a"

    return f"p50 {cell('p50')} / p95 {cell('p95')} / p99 {cell('p99')} ms"


def render_envelope(
    config,
    run_meta: RunMeta,
    deployment: DeploymentShape,
    stats_summary: dict[str, Any],
    metrics,
    conclusion: Conclusion,
) -> str:
    lines: list[str] = []
    lines.append("# Event Load Envelope Report")
    lines.append("")
    lines.append(
        "Generated by the #926 event-load harness. Numbers below are client-measured "
        "unless attributed to a provider source. Missing signals are listed as gaps, not guessed."
    )
    lines.append("")

    lines.append("## Target environment and run parameters")
    lines.append("")
    lines.append(f"- Target: `{config.target_url}` (environment `{config.environment}`)")
    lines.append(f"- Profile: `{config.profile}`")
    lines.append(
        f"- Concurrency: {config.concurrency} | ramp: {config.ramp_seconds}s | duration: {config.duration_seconds}s"
    )
    lines.append(f"- Run window: {run_meta.started_at} -> {run_meta.ended_at}")
    lines.append(f"- Git SHA: {_u(run_meta.git_sha)} | image digest: {_u(run_meta.image_digest)}")
    lines.append(f"- Metric source: `{config.metric_source}`")
    lines.append("")

    lines.append("## Deployment shape")
    lines.append("")
    lines.append(f"- Portal instances/pods: {_u(deployment.instances)}")
    lines.append(f"- Process/worker model: {_u(deployment.process_model)}")
    lines.append(f"- Terminal caps: {_u(deployment.terminal_caps)}")
    lines.append(f"- Redis posture: {_u(deployment.redis_posture)}")
    lines.append(f"- RDS posture: {_u(deployment.rds_posture)}")
    lines.append(f"- Guacamole posture: {_u(deployment.guacamole_posture)}")
    lines.append("")

    lines.append("## Client-measured results (per route)")
    lines.append("")
    routes = stats_summary.get("routes", {})
    if routes:
        lines.append("| Route | Requests | OK | Errors | Latency | WebSocket |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for name, r in routes.items():
            ws_cell = "-"
            if "close_codes" in r:
                codes = ", ".join(f"{k}:{v}" for k, v in r["close_codes"].items())
                ws_cell = (
                    f"opened {r.get('ws_opened', 0)}, dropped {r.get('ws_dropped', 0)}, "
                    f"reconnects {r.get('reconnects', 0)} [{codes}]"
                )
            lines.append(
                f"| `{name}` | {r['requests']} | {r['ok']} | {r['errors']} | "
                f"{_fmt_latency(r['latency_ms'])} | {ws_cell} |"
            )
    else:
        lines.append("_No route results recorded._")
    totals = stats_summary.get("totals", {})
    lines.append("")
    lines.append(
        f"Totals: {totals.get('requests', 0)} requests, {totals.get('ok', 0)} ok, {totals.get('errors', 0)} errors."
    )
    lines.append("")

    lines.append("## Provider metrics (same window)")
    lines.append("")
    lines.append(f"Provider: `{metrics.provider}` | window {metrics.window_start} -> {metrics.window_end}")
    lines.append("")
    if metrics.metrics:
        lines.append("| Signal | Value | Unit | Provenance | Proxy? |")
        lines.append("| --- | --- | --- | --- | --- |")
        for mv in metrics.metrics.values():
            lines.append(f"| {mv.name} | {mv.value} | {mv.unit} | {mv.provenance} | {'yes' if mv.is_proxy else 'no'} |")
        lines.append("")
    if metrics.gaps:
        lines.append("Gaps (signals not collected in this run):")
        lines.append("")
        for gap in metrics.gaps:
            lines.append(f"- {gap}")
        lines.append("")

    lines.append("## Conclusion")
    lines.append("")
    lines.append(f"- Supported concurrency: {conclusion.supported_concurrency}")
    lines.append(f"- Margin: {conclusion.margin}")
    lines.append(f"- Limiting factor: {conclusion.limiting_factor}")
    lines.append(f"- First-mover signal: {conclusion.first_mover_signal}")
    lines.append(f"- Sizing implication (#910): {conclusion.sizing_implication}")
    lines.append("")

    report = "\n".join(lines)
    _assert_sanitized(report)
    return report


def derive_conclusion(config, stats_summary: dict[str, Any]) -> Conclusion:
    """Heuristically derive a supported-concurrency conclusion from one run's evidence.

    This is an honest first pass, not a verdict: a single run can show saturation
    or its absence at the target concurrency, but bounding the true ceiling and
    margin needs a stepped-concurrency sweep. The operator refines from the
    evidence table; the harness fills what the data actually supports.
    """
    target = config.concurrency
    routes = stats_summary.get("routes", {})

    ws_unavailable = False
    server_errors = False
    rate_limited = False
    transport_errors = False
    for r in routes.values():
        for code in r.get("close_codes", {}):
            if code in ("SERVICE_UNAVAILABLE", "SSH_CONNECTION_FAILED", "SERVER_ERROR"):
                ws_unavailable = True
        categories = r.get("errors_by_category", {})
        if "server_error" in categories or "service_unavailable" in categories:
            server_errors = True
        if "rate_limited" in categories:
            rate_limited = True
        if "transport_error" in categories or "executor_error" in categories:
            transport_errors = True

    if ws_unavailable:
        limiting = "terminal/websocket capacity (SERVICE_UNAVAILABLE / SSH-failure close codes)"
        first_mover = "websocket close codes appeared before broad HTTP failure"
        saturated = True
    elif server_errors:
        limiting = "portal server errors (5xx) under load"
        first_mover = "HTTP 5xx / service_unavailable responses"
        saturated = True
    elif rate_limited:
        limiting = "edge/WAF or application rate limiting (429)"
        first_mover = "HTTP 429 responses"
        saturated = True
    elif transport_errors:
        limiting = "elevated client/transport errors (could be client-side; verify client resource limits)"
        first_mover = "transport-layer failures"
        saturated = True
    else:
        limiting = "no saturation observed at target concurrency"
        first_mover = "none observed at this concurrency"
        saturated = False

    if saturated:
        supported = f"below {target} (saturation observed at the target concurrency)"
    else:
        supported = f"at least {target} (no saturation observed; raise concurrency to find the ceiling)"

    return Conclusion(
        supported_concurrency=supported,
        margin="unknown from a single run; re-run at stepped concurrency to bound the margin",
        limiting_factor=limiting,
        sizing_implication=f"feed into #910 sizing: {limiting}",
        first_mover_signal=first_mover,
    )


def _assert_sanitized(text: str) -> None:
    for pattern in _SECRET_PATTERNS:
        if pattern.search(text):
            raise ReportError(
                "report sanitization refused: content matched a secret pattern "
                f"({pattern.pattern!r}); fix the input rather than committing a leaky report"
            )
