#!/usr/bin/env python3
"""Render the generated GKE NetworkPolicy that authorizes platform pods
to reach the Cloud SQL and Memorystore private-service endpoints.

The `_gcp-dev.yml` workflow applies the platform Kubernetes manifests with
`kubectl apply -k` against `platform/k8s/gcp/overlays/<env>`, which does
not have Terraform-output templating. The Cloud SQL and Memorystore private
IPs come out of `terraform apply` and are dynamic, so an egress NetworkPolicy
authorizing those endpoints must be generated at deploy time and shipped
alongside the existing `platform-runtime.generated.env` and
`platform-edge.generated.yaml`.

Output: a single NetworkPolicy ("allow-platform-private-service-egress")
in the `shifter-platform` namespace, with per-host `/32` ipBlocks for the
Cloud SQL and Memorystore private IPs, plus the GKE services CIDR (used by
restricted.googleapis.com). Ports: 5432 (Cloud SQL), 6378 (Memorystore TLS,
ADR-008-R6), and 6379 (plaintext Redis, kept for compatibility with
pre-#963 environments). The narrow per-host CIDRs match the Helm chart's
`privateServiceCidrs` flow in `scripts/bootstrap/deploy.py` so the two
deploy paths share the same private-service contract.
"""

from __future__ import annotations

import argparse
import json
from ipaddress import ip_address
from pathlib import Path


def _value(outputs: dict[str, object], key: str):
    try:
        return outputs[key]["value"]
    except KeyError as exc:
        raise KeyError(f"Missing Terraform output: {key}") from exc


def _host_as_single_address_cidr(host: object) -> str:
    """Return the host string as a `<addr>/32` CIDR (or `<addr>/128` for IPv6).

    Mirrors `scripts/bootstrap/deploy.py::_host_as_single_address_cidr` so the
    Kustomize-rendered NetworkPolicy and the Helm-rendered chart values agree
    on the per-endpoint CIDR shape.
    """
    if not isinstance(host, str) or not host.strip():
        raise ValueError(f"expected a non-empty host string, got: {host!r}")
    addr = ip_address(host.strip())
    return f"{addr.exploded}/{32 if addr.version == 4 else 128}"


def render_netpol(outputs: dict[str, object]) -> str:
    """Return the YAML for the platform private-service egress NetworkPolicy.

    Sources are the same Terraform outputs `bootstrap/deploy.py` consumes
    for the Helm chart's `privateServiceCidrs` list, so the two deploy
    paths converge on a single private-service contract.
    """
    database = _value(outputs, "control_plane_database")
    cache = _value(outputs, "control_plane_cache")
    guacamole_database = _value(outputs, "guacamole_database")
    gke_services_cidr = str(_value(outputs, "gke_services_cidr")).strip()

    if not gke_services_cidr:
        raise ValueError(
            "gke_services_cidr Terraform output must be non-empty; refusing to render "
            "a NetworkPolicy without the GKE services range"
        )

    seen: set[str] = set()
    ordered_cidrs: list[str] = []
    for host_value in (
        database.get("private_ip"),
        cache.get("host"),
        guacamole_database.get("host"),
    ):
        cidr = _host_as_single_address_cidr(host_value)
        if cidr not in seen:
            seen.add(cidr)
            ordered_cidrs.append(cidr)
    if gke_services_cidr not in seen:
        seen.add(gke_services_cidr)
        ordered_cidrs.append(gke_services_cidr)

    ip_blocks = "\n".join(f"        - ipBlock:\n            cidr: {cidr}" for cidr in ordered_cidrs)

    # YAML is hand-formatted (rather than via PyYAML) for two reasons:
    # the manifest is short and structurally fixed, and the workflow runs
    # in a minimal Python environment where adding PyYAML to the runtime
    # pip env would expand surface for marginal gain.
    return f"""# This file is generated by scripts/gcp/render_private_service_netpol.py.
# Do not edit by hand. The source of truth is the Terraform-output set
# produced by `terraform apply` in `platform/terraform/gcp/environments/<env>`.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-platform-private-service-egress-generated
  namespace: shifter-platform
  labels:
    app.kubernetes.io/name: shifter
    app.kubernetes.io/part-of: shifter
spec:
  podSelector: {{}}
  policyTypes:
    - Egress
  egress:
    - to:
{ip_blocks}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          # Plaintext Redis (pre-#963 / AWS path).
          port: 6379
        - protocol: TCP
          # Memorystore TLS endpoint (ADR-008-R6, #963).
          port: 6378
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--terraform-output-json", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    outputs = json.loads(args.terraform_output_json.read_text())
    rendered = render_netpol(outputs)
    args.output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
