# Generated by Django 6.0 on 2025-12-14

from django.db import migrations, models


def grant_kali_ssh_key(apps, schema_editor):
    """Grant UPDATE permission on kali_ssh_key_secret_arn (PostgreSQL only)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        GRANT UPDATE (kali_ssh_key_secret_arn) ON mission_control_range TO provisioner_lambda;
    """)


def revoke_kali_ssh_key(apps, schema_editor):
    """Revoke UPDATE permission on kali_ssh_key_secret_arn (PostgreSQL only)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        REVOKE UPDATE (kali_ssh_key_secret_arn) ON mission_control_range FROM provisioner_lambda;
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("mission_control", "0009_grant_kali_columns_to_provisioner"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="kali_ssh_key_secret_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secrets Manager ARN for Kali SSH private key",
                max_length=500,
            ),
        ),
        # Grant provisioner_lambda permission to update this column
        migrations.RunPython(grant_kali_ssh_key, revoke_kali_ssh_key),
    ]
