# Generated by Django 6.0 on 2025-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0015_grant_victim_ssh_key_to_provisioner"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="instance_config",
            field=models.JSONField(
                blank=True,
                help_text="JSON array of instance configurations for Pulumi provisioner",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="provisioned_instances",
            field=models.JSONField(
                blank=True,
                help_text="JSON array of provisioned instance details from Pulumi",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="provisioner_version",
            field=models.CharField(
                default="v1",
                help_text="Provisioner version: v1=Lambda, v2=Pulumi",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="pulumi_stack",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pulumi stack name for this range",
                max_length=255,
            ),
        ),
    ]
