# Generated by Django 6.0 on 2025-12-25 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0020_grant_ngfw_columns_to_provisioner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NGFWConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for this config", max_length=100
                    ),
                ),
                (
                    "panorama_server",
                    models.CharField(
                        help_text="Primary Panorama IP or FQDN", max_length=255
                    ),
                ),
                (
                    "vm_auth_key",
                    models.CharField(
                        help_text="VM auth key from Panorama", max_length=255
                    ),
                ),
                (
                    "panorama_server_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Secondary Panorama (HA)",
                        max_length=255,
                    ),
                ),
                (
                    "template_stack",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Template stack name",
                        max_length=100,
                    ),
                ),
                (
                    "device_group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Device group name",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngfw_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NGFW Config",
                "verbose_name_plural": "NGFW Configs",
                "ordering": ["-created_at"],
            },
        ),
    ]
