# Generated by Django 6.0 on 2026-01-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0032_move_userprofile_activitylog_to_management"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userngfw",
            name="deployment_profile",
        ),
        migrations.RemoveField(
            model_name="userngfw",
            name="scm_credential",
        ),
        migrations.AlterField(
            model_name="agentconfig",
            name="name",
            field=models.CharField(help_text="User-friendly name", max_length=100),
        ),
    ]
