# Generated by Django 6.0 on 2026-01-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0033_remove_credential_fks_from_userngfw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scmcredential",
            name="user",
        ),
        migrations.DeleteModel(
            name="NGFWDeploymentProfile",
        ),
        migrations.DeleteModel(
            name="SCMCredential",
        ),
    ]
