# Generated by Django 6.0 on 2026-01-01 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_rangeinstance_agent_fk"),
        ("mission_control", "0033_remove_credential_fks_from_userngfw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentconfig",
            name="os",
        ),
        migrations.RemoveField(
            model_name="agentconfig",
            name="user",
        ),
        migrations.AlterField(
            model_name="range",
            name="dc_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent for DC instances (Windows only, required for AD scenarios)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dc_ranges",
                to="cms.agentconfig",
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent for victim instances",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ranges",
                to="cms.agentconfig",
            ),
        ),
        migrations.RemoveField(
            model_name="ngfwdeploymentprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="scmcredential",
            name="user",
        ),
        migrations.DeleteModel(
            name="OperatingSystem",
        ),
        migrations.DeleteModel(
            name="AgentConfig",
        ),
        migrations.DeleteModel(
            name="NGFWDeploymentProfile",
        ),
        migrations.DeleteModel(
            name="SCMCredential",
        ),
    ]
