"""Render the range egress policy into provider Terraform bridge variables (#958).

``settings.range_egress`` in ``shifter.yaml`` is the single authoritative operator
intent for range network egress (PLAT-220, ADR-017). The provider-specific Terraform
*bridge* variables that the firewall modules consume are an implementation detail, not a
second configuration surface. Before #958 those bridge values were hand-maintained in a
gitignored ``*.auto.tfvars`` copy alongside the public policy, so the two could drift.

This module closes that drift: it consumes the normalized :class:`RangeEgressPolicy`
(via :func:`installation.loader.load_root_config`) and emits the bridge ``.tfvars`` for
the config's backend, so the deployed firewall rules are generated from the configured
policy rather than transcribed by hand (ADR-017-R4).

- AWS bridges into ``range_egress_mode`` (runtime route-table posture: ``allowlist`` or
  ``none``) and ``victim_allowed_cidrs`` (consumed by the AWS Network Firewall rule
  groups in ``platform/terraform/modules/range/vpc/firewall.tf``). ``status-quo``,
  ``allowlist``, and ``deny-all`` map to runtime ``allowlist``; ``none`` maps to
  runtime ``none`` (no default route). ``allowlist`` renders the canonical CIDRs;
  other modes render an empty list.
- GCP bridges into ``range_egress_mode`` + ``range_egress_allowed_cidrs`` (consumed by
  the conditional VPC firewall egress rules in
  ``platform/terraform/gcp/modules/platform-core/main.tf``).

The values are already constrained to canonical CIDR strings and a fixed mode enum by
:class:`RangeEgressPolicy`, so the emitted HCL is trusted: a valid CIDR or mode value
carries no quote, backslash, or newline that could break out of the rendered literal.
The renderer never reads or revalidates raw YAML and never maintains a second schema.

This module also emits :func:`render_cloud_provider_tfvars` (PLAT-2005): the renderer-owned
``cloud_provider`` tfvar derived from ``config.backend``, so the runtime cloud-provider
identity is a rendered output of the validated installation config rather than a
hardcoded literal or a branch-name inference. It is a separate tfvar for a separate
consumer from the range-egress bridge above.
"""

from __future__ import annotations

import json

from . import warm_pool
from .errors import ConfigIssue, InstallationConfigError
from .range_egress import SETTINGS_KEY, RangeEgressMode, RangeEgressPolicy, aws_runtime_egress_mode
from .schema import RootConfig
from .settings_gcp import GcpBackendSettings

_WARM_POOL_ENV_HEADER = (
    "# Generated by `shifter-config render-warm-pool-env` from shifter.yaml settings.warm_pool.\n"
    "# Do not edit by hand; re-run the renderer to update. The warm-pool policy is\n"
    "# operator configuration, not secrets.\n"
)

_HEADER = (
    "# Generated by `shifter-config render` from shifter.yaml settings.range_egress.\n"
    "# Do not edit by hand; re-run the renderer to update. CIDRs are operator\n"
    "# configuration, not secrets.\n"
)

_CLOUD_PROVIDER_HEADER = (
    "# Generated by `shifter-config render-runtime` from shifter.yaml's selected backend.\n"
    "# Do not edit by hand; re-run the renderer to update. The backend name is a validated\n"
    "# enum value, not a secret.\n"
)


def render_tfvars(config: RootConfig) -> str:
    """Render the Terraform bridge ``.tfvars`` for ``config``'s backend.

    ``config`` should come from :func:`installation.loader.load_root_config`, which
    normalizes ``settings.range_egress`` to the canonical policy shape.

    Raises:
        InstallationConfigError: if the backend has no range-egress renderer, or if
            ``mode='none'`` is requested on an unsupported backend.
    """
    policy = _policy_from_config(config)
    if policy.mode == RangeEgressMode.NONE and config.backend != "aws":
        raise InstallationConfigError(
            [
                ConfigIssue(
                    f"settings.{SETTINGS_KEY}.mode",
                    "mode='none' (zero-egress route posture) is supported on AWS only; "
                    f"backend {config.backend!r} does not implement it yet",
                )
            ]
        )
    renderer = _RENDERERS.get(config.backend)
    if renderer is None:
        raise InstallationConfigError(
            [ConfigIssue("backend", f"no range egress renderer for backend {config.backend!r}")]
        )
    rendered = renderer(policy)
    if config.backend == "gcp":
        # Re-enter the closed GCP model so Python uses identifiers that distinguish
        # public project/resource metadata from credential payloads. The model's
        # aliases preserve the existing YAML and Terraform wire contract.
        gcp_settings = GcpBackendSettings.from_root_settings(config.settings)
        dynamic_project = gcp_settings.range_resource_project_id
        rendered += f'dynamic_secret_project_id = "{dynamic_project}"\n'
        static_refs = gcp_settings.provisioner_static_resource_refs
        rendered += _hcl_string_map("provisioner_static_secret_refs", dict(static_refs))
        broker = gcp_settings.model_broker.model_dump(mode="json")
        rendered += "model_broker = " + json.dumps(broker, separators=(",", ":"), sort_keys=True) + "\n"
    return _HEADER + rendered


def render_cloud_provider_tfvars(config: RootConfig) -> str:
    """Render the renderer-owned ``cloud_provider`` Terraform bridge tfvar.

    ``config`` should come from :func:`installation.loader.load_root_config`, which
    validates ``backend`` against the registry's known backend names (PLAT-2002). This is
    the single renderer-owned source of the runtime cloud-provider identity: the AWS
    Terraform bridge consumes this tfvar instead of an implicit default or a branch name,
    matching how the GCP backend already derives its own equivalent value in
    ``scripts/gcp/render_runtime_env.py``. It is deliberately separate from
    :func:`render_tfvars` (the ``settings.range_egress`` bridge) — a different tfvar for a
    different consumer, generated from a different part of the validated config.

    ``config.backend`` is already constrained to a known enum-like value by
    ``load_root_config``, so the emitted HCL is trusted: no quote, backslash, or newline
    can appear in a valid backend name, and no additional escaping is needed.
    """
    return _CLOUD_PROVIDER_HEADER + f'cloud_provider = "{config.backend}"\n'


def _policy_from_config(config: RootConfig) -> RangeEgressPolicy:
    """Extract the range egress policy from a (normalized) root config.

    An absent block is the documented ``status-quo`` default.
    """
    raw = config.settings.get(SETTINGS_KEY)
    if raw is None:
        return RangeEgressPolicy()
    return RangeEgressPolicy.model_validate(raw)


def _render_aws(policy: RangeEgressPolicy) -> str:
    """Render the AWS bridge tfvars for ``policy``."""
    mode = f'range_egress_mode = "{aws_runtime_egress_mode(policy)}"\n'
    cidrs = _hcl_string_list("victim_allowed_cidrs", policy.allowed_cidrs)
    return mode + cidrs


def _render_gcp(policy: RangeEgressPolicy) -> str:
    """Render the GCP bridge tfvars (``range_egress_mode`` + ``range_egress_allowed_cidrs``)."""
    mode = f'range_egress_mode = "{policy.mode.value}"\n'
    cidrs = _hcl_string_list("range_egress_allowed_cidrs", policy.allowed_cidrs)
    return mode + cidrs


_RENDERERS = {
    "aws": _render_aws,
    "gcp": _render_gcp,
}


def _hcl_string_list(name: str, values: list[str]) -> str:
    """Render ``name = [...]`` as Terraform-valid HCL.

    Empty lists render inline (``name = []``); non-empty lists render one quoted entry
    per line with a trailing comma, preserving the policy's order.
    """
    if not values:
        return f"{name} = []\n"
    lines = [f"{name} = ["]
    lines.extend(f'  "{value}",' for value in values)
    lines.append("]")
    return "\n".join(lines) + "\n"


def _hcl_string_map(name: str, values: dict[str, str]) -> str:
    """Render a validated string map as stable Terraform HCL."""
    if not values:
        return f"{name} = {{}}\n"
    lines = [f"{name} = {{"]
    lines.extend(f'  {key} = "{values[key]}"' for key in sorted(values))
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_warm_pool_env(config: RootConfig) -> str:
    """Render the validated ``settings.warm_pool`` policy into the runtime env line.

    Emits a single ``WARM_POOL_POLICY_JSON=<json>`` line (compact JSON) that the
    deploy pipeline injects into the ``platform-runtime`` ConfigMap the portal and
    warm-pool reconciler consume. This is the canonical publication of the
    install-time-validated policy into the runtime (#28): an omitted block renders
    the disabled projection, so a missing block boots disabled rather than silently
    dropping a configured policy. The renderer, not a hand-maintained env file, is
    the source of truth, exactly as ``render`` owns the range_egress tfvars.
    """
    import json

    raw = config.settings.get(warm_pool.SETTINGS_KEY)
    policy = warm_pool.WarmPoolPolicy.model_validate(dict(raw) if isinstance(raw, dict) else {})
    projection = warm_pool.runtime_projection(policy)
    encoded = json.dumps(projection, separators=(",", ":"), sort_keys=True)
    return f"{_WARM_POOL_ENV_HEADER}WARM_POOL_POLICY_JSON={encoded}\n"


def render_model_access_catalog(config: RootConfig) -> str:
    """Render the validated non-secret catalog as a dedicated mounted artifact."""
    import json

    from . import model_access

    raw = config.settings.get(model_access.SETTINGS_KEY)
    if not isinstance(raw, dict) or not isinstance(raw.get("catalog"), dict):
        return ""
    return json.dumps(raw["catalog"], separators=(",", ":"), sort_keys=True, ensure_ascii=False) + "\n"


def render_model_access_env(config: RootConfig) -> str:
    """Render activation plus catalog path/digest without placing the body in env."""
    from . import model_access

    raw = config.settings.get(model_access.SETTINGS_KEY)
    if not isinstance(raw, dict) or not isinstance(raw.get("catalog"), dict):
        return "MODEL_ACCESS_ENABLED=false\nMODEL_ACCESS_CATALOG_PATH=\nMODEL_ACCESS_CATALOG_DIGEST=\n"
    enabled = "true" if raw.get("enabled") is True else "false"
    digest = raw["catalog"]["digest"]
    return (
        f"MODEL_ACCESS_ENABLED={enabled}\n"
        f"MODEL_ACCESS_CATALOG_PATH={model_access.DEFAULT_CATALOG_PATH}\n"
        f"MODEL_ACCESS_CATALOG_DIGEST={digest}\n"
    )


def render_mission_control_lease_env(config: RootConfig) -> str:
    """Render the validated ``settings.mission_control_leases`` policy as a runtime env line.

    Emits a single ``MISSION_CONTROL_LEASE_POLICY_JSON=<compact json>`` line consumed by
    the AWS and GCP runtime producers and delivered into the ``platform-runtime`` ConfigMap
    (issue #27, ADR-011-R9). An omitted block renders the canonical 30/30/365 defaults, so a
    missing block boots backward-compatibly rather than dropping a configured policy. Like
    ``render_model_access_env`` this emits exactly one ``KEY=VALUE`` line (no header comment),
    because the producers split each rendered line on ``=``.
    """
    from shared.mission_control_lease import MissionControlLeasePolicy, dump_policy_json

    from . import mission_control_lease

    settings = config.settings
    if mission_control_lease.SETTINGS_KEY not in settings:
        # Truly absent -> canonical defaults. An explicit null / non-mapping block is
        # rejected by the loader's shared-block validation before render, so a present
        # value here is the normalized policy mapping (never None), not an omission.
        policy = MissionControlLeasePolicy()
    else:
        policy = MissionControlLeasePolicy.model_validate(dict(settings[mission_control_lease.SETTINGS_KEY]))
    return f"MISSION_CONTROL_LEASE_POLICY_JSON={dump_policy_json(policy)}\n"
