"""Render the range egress policy into provider Terraform bridge variables (#958).

``settings.range_egress`` in ``shifter.yaml`` is the single authoritative operator
intent for range network egress (PLAT-220, ADR-017). The provider-specific Terraform
*bridge* variables that the firewall modules consume are an implementation detail, not a
second configuration surface. Before #958 those bridge values were hand-maintained in a
gitignored ``*.auto.tfvars`` copy alongside the public policy, so the two could drift.

This module closes that drift: it consumes the normalized :class:`RangeEgressPolicy`
(via :func:`installation.loader.load_root_config`) and emits the bridge ``.tfvars`` for
the config's backend, so the deployed firewall rules are generated from the configured
policy rather than transcribed by hand (ADR-017-R4).

- AWS bridges into ``range_egress_mode`` (runtime route-table posture: ``allowlist`` or
  ``none``) and ``victim_allowed_cidrs`` (consumed by the AWS Network Firewall rule
  groups in ``platform/terraform/modules/range/vpc/firewall.tf``). ``status-quo``,
  ``allowlist``, and ``deny-all`` map to runtime ``allowlist``; ``none`` maps to
  runtime ``none`` (no default route). ``allowlist`` renders the canonical CIDRs;
  other modes render an empty list.
- GCP bridges into ``range_egress_mode`` + ``range_egress_allowed_cidrs`` (consumed by
  the conditional VPC firewall egress rules in
  ``platform/terraform/gcp/modules/platform-core/main.tf``).

The values are already constrained to canonical CIDR strings and a fixed mode enum by
:class:`RangeEgressPolicy`, so the emitted HCL is trusted: a valid CIDR or mode value
carries no quote, backslash, or newline that could break out of the rendered literal.
The renderer never reads or revalidates raw YAML and never maintains a second schema.
"""

from __future__ import annotations

from .errors import ConfigIssue, InstallationConfigError
from .range_egress import SETTINGS_KEY, RangeEgressMode, RangeEgressPolicy, aws_runtime_egress_mode
from .schema import RootConfig

_HEADER = (
    "# Generated by `shifter-config render` from shifter.yaml settings.range_egress.\n"
    "# Do not edit by hand; re-run the renderer to update. CIDRs are operator\n"
    "# configuration, not secrets.\n"
)


def render_tfvars(config: RootConfig) -> str:
    """Render the Terraform bridge ``.tfvars`` for ``config``'s backend.

    ``config`` should come from :func:`installation.loader.load_root_config`, which
    normalizes ``settings.range_egress`` to the canonical policy shape.

    Raises:
        InstallationConfigError: if the backend has no range-egress renderer, or if
            ``mode='none'`` is requested on an unsupported backend.
    """
    policy = _policy_from_config(config)
    if policy.mode == RangeEgressMode.NONE and config.backend != "aws":
        raise InstallationConfigError(
            [
                ConfigIssue(
                    f"settings.{SETTINGS_KEY}.mode",
                    "mode='none' (zero-egress route posture) is supported on AWS only; "
                    f"backend {config.backend!r} does not implement it yet",
                )
            ]
        )
    renderer = _RENDERERS.get(config.backend)
    if renderer is None:
        raise InstallationConfigError(
            [ConfigIssue("backend", f"no range egress renderer for backend {config.backend!r}")]
        )
    return _HEADER + renderer(policy)


def _policy_from_config(config: RootConfig) -> RangeEgressPolicy:
    """Extract the range egress policy from a (normalized) root config.

    An absent block is the documented ``status-quo`` default.
    """
    raw = config.settings.get(SETTINGS_KEY)
    if raw is None:
        return RangeEgressPolicy()
    return RangeEgressPolicy.model_validate(raw)


def _render_aws(policy: RangeEgressPolicy) -> str:
    """Render the AWS bridge tfvars for ``policy``."""
    mode = f'range_egress_mode = "{aws_runtime_egress_mode(policy)}"\n'
    cidrs = _hcl_string_list("victim_allowed_cidrs", policy.allowed_cidrs)
    return mode + cidrs


def _render_gcp(policy: RangeEgressPolicy) -> str:
    """Render the GCP bridge tfvars (``range_egress_mode`` + ``range_egress_allowed_cidrs``)."""
    mode = f'range_egress_mode = "{policy.mode.value}"\n'
    cidrs = _hcl_string_list("range_egress_allowed_cidrs", policy.allowed_cidrs)
    return mode + cidrs


_RENDERERS = {
    "aws": _render_aws,
    "gcp": _render_gcp,
}


def _hcl_string_list(name: str, values: list[str]) -> str:
    """Render ``name = [...]`` as Terraform-valid HCL.

    Empty lists render inline (``name = []``); non-empty lists render one quoted entry
    per line with a trailing comma, preserving the policy's order.
    """
    if not values:
        return f"{name} = []\n"
    lines = [f"{name} = ["]
    lines.extend(f'  "{value}",' for value in values)
    lines.append("]")
    return "\n".join(lines) + "\n"
