apiVersion: v1
kind: Pod
metadata:
  name: l2-probe-same-node
  namespace: vmrt-mixed-subnet
  annotations:
    k8s.v1.cni.cncf.io/networks: vmrt-shared-l2
spec:
  nodeSelector:
    kubernetes.io/hostname: cluster1-abm-w1-001
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      command:
        - /bin/sh
        - -c
        - sleep infinity
---
apiVersion: v1
kind: Pod
metadata:
  name: l2-probe-cross-node
  namespace: vmrt-mixed-subnet
  annotations:
    k8s.v1.cni.cncf.io/networks: vmrt-shared-l2
spec:
  nodeSelector:
    kubernetes.io/hostname: cluster1-abm-w2-001
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      command:
        - /bin/sh
        - -c
        - sleep infinity
