#!/usr/bin/env bash
# Fetch GCP IP ranges and generate Terraform variable file for firewall allowlist
#
# Sources:
# - https://www.gstatic.com/ipranges/cloud.json (GCP Cloud services)
# - https://www.gstatic.com/ipranges/goog.json (Google services)
#
# Output: victim_allowed_cidrs.auto.tfvars with all IPv4 CIDRs
#
# Usage: ./update-gcp-ip-ranges.sh [output_dir]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${1:-$(dirname "$SCRIPT_DIR")}"
OUTPUT_FILE="${OUTPUT_DIR}/victim_allowed_cidrs.auto.tfvars"

CLOUD_JSON_URL="https://www.gstatic.com/ipranges/cloud.json"
GOOG_JSON_URL="https://www.gstatic.com/ipranges/goog.json"

# Additional IPs not in GCP ranges
ADDITIONAL_IPS=(
    "159.183.150.248/32"  # PANW email notification server
    "8.8.8.8/32"          # Google DNS (for testing)
)

echo "Fetching GCP IP ranges..."

# Fetch and extract IPv4 prefixes from both sources
CLOUD_CIDRS=$(curl -s "$CLOUD_JSON_URL" | jq -r '.prefixes[].ipv4Prefix // empty' | sort -u)
GOOG_CIDRS=$(curl -s "$GOOG_JSON_URL" | jq -r '.prefixes[].ipv4Prefix // empty' | sort -u)

# Combine, dedupe, and sort
ALL_CIDRS=$(echo -e "${CLOUD_CIDRS}\n${GOOG_CIDRS}" | sort -u | grep -v '^$')

# Count
CLOUD_COUNT=$(echo "$CLOUD_CIDRS" | grep -c '^' || echo 0)
GOOG_COUNT=$(echo "$GOOG_CIDRS" | grep -c '^' || echo 0)
TOTAL_COUNT=$(echo "$ALL_CIDRS" | grep -c '^' || echo 0)

echo "  Cloud ranges: $CLOUD_COUNT"
echo "  Google ranges: $GOOG_COUNT"
echo "  Combined unique: $TOTAL_COUNT"
echo "  Additional IPs: ${#ADDITIONAL_IPS[@]}"

# Generate Terraform variable file
cat > "$OUTPUT_FILE" << 'HEADER'
# Auto-generated file - DO NOT EDIT MANUALLY
# Generated by: scripts/update-gcp-ip-ranges.sh
# Sources:
#   - https://www.gstatic.com/ipranges/cloud.json
#   - https://www.gstatic.com/ipranges/goog.json
#
# This file contains all GCP IP ranges used by Palo Alto Networks services
# (Cortex XDR/XSIAM, SCM, etc.) plus additional required IPs.
#
# To regenerate: ./scripts/update-gcp-ip-ranges.sh

victim_allowed_cidrs = [
HEADER

# Add GCP CIDRs
echo "$ALL_CIDRS" | while read -r cidr; do
    echo "  \"$cidr\","
done >> "$OUTPUT_FILE"

# Add additional IPs
for ip in "${ADDITIONAL_IPS[@]}"; do
    echo "  \"$ip\",  # Additional required IP"
done >> "$OUTPUT_FILE"

echo "]" >> "$OUTPUT_FILE"

# Add generation timestamp as comment
echo "" >> "$OUTPUT_FILE"
echo "# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$OUTPUT_FILE"

FINAL_COUNT=$((TOTAL_COUNT + ${#ADDITIONAL_IPS[@]}))
echo ""
echo "Generated: $OUTPUT_FILE"
echo "Total CIDRs: $FINAL_COUNT"
