import { PrismaClient } from '../../generated/prisma';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export class ChatChannelsGenerator {
  constructor(private prisma: PrismaClient) {}

  async generate(): Promise<void> {
    // Load static data from JSON
    const staticDataPath = path.join(__dirname, '../../data/static-data.json');
    const staticData = JSON.parse(fs.readFileSync(staticDataPath, 'utf8'));
    
    // Clear existing data
    await this.prisma.chat_channels.deleteMany({});
    
    // Insert channels from JSON (only use fields that exist in schema)
    const transformedChannels = staticData.chat_channels.map((channel: any) => ({
      name: channel.name,
      description: channel.description,
      // created_at will be auto-generated by default
    }));
    
    await this.prisma.chat_channels.createMany({
      data: transformedChannels,
    });
  }
}
