# Generated by Django 6.0 on 2026-02-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="source_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("restore", "Restore"),
                    ("close", "Close"),
                    ("reopen", "Reopen"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("access_denied", "Access Denied"),
                    ("connect", "Connect"),
                    ("disconnect", "Disconnect"),
                    ("provision", "Provision"),
                    ("deprovision", "Deprovision"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                    ("pause", "Pause"),
                    ("resume", "Resume"),
                    ("cancel", "Cancel"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("apikey", "API Key"),
                    ("system", "System"),
                    ("cognito", "Cognito"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("risk", "Risk"),
                    ("comment", "Comment"),
                    ("apikey", "API Key"),
                    ("range", "Range"),
                    ("credential", "Credential"),
                    ("agent", "Agent"),
                    ("user", "User"),
                    ("session", "Session"),
                    ("ngfw", "NGFW"),
                    ("config", "Configuration"),
                    ("experiment", "Experiment"),
                    ("scenario", "Scenario"),
                    ("script", "Script"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="risk_regist_action_b646cf_idx"),
        ),
    ]
