# Generated by Django 6.0.6 on 2026-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0003_alter_comment_options_alter_risk_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('close', 'Close'), ('reopen', 'Reopen'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('access_denied', 'Access Denied'), ('role_sync', 'Role Sync'), ('connect', 'Connect'), ('disconnect', 'Disconnect'), ('provision', 'Provision'), ('deprovision', 'Deprovision'), ('ready', 'Ready'), ('failed', 'Failed'), ('pause', 'Pause'), ('resume', 'Resume'), ('cancel', 'Cancel')], max_length=20),
        ),
    ]
