# Generated by Django 6.0.4 on 2026-05-03 15:59

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0003_alter_comment_options_alter_risk_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='risk',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
