# Generated by Django 6.0.8 on 2026-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_userprofile_ctf_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Temporary-suspension discriminator (issue #1943). When set, the account is suspended: authentication is blocked (User.is_active is held False) while assignments and owned resources are retained. It distinguishes a reversible security hold from a plain deactivation and from soft deletion; User.is_active remains the sole authentication-enforcement bit.', null=True),
        ),
    ]
