# Generated by Django 6.0.8 on 2026-09-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("management", "0012_disable_soft_deleted_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelAccessGroupEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("managed_membership", models.BooleanField(default=False)),
                ("spending_approved", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_access_eligibility",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "management_model_access_group_eligibility",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gt", 0)),
                        name="management_model_access_group_revision_positive",
                    )
                ],
            },
        ),
    ]
