# Generated by Django 6.0.6 on 2026-06-23 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-friendly name for this token', max_length=100)),
                ('token_id', models.CharField(help_text='Public lookup id (the part after the prefix); not a secret', max_length=32, unique=True)),
                ('verifier_hash', models.CharField(help_text='SHA-256 verifier of the token secret', max_length=64)),
                ('scopes', models.JSONField(default=list, help_text='Granted scopes from the central registry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'shared_api_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_id'], name='shared_api__token_i_f68afd_idx'), models.Index(fields=['created_by', 'revoked_at'], name='shared_api__created_8fafb0_idx'), models.Index(fields=['expires_at'], name='shared_api__expires_ce6869_idx')],
            },
        ),
    ]
