# Generated by Django 6.0.6 on 2026-07-05 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcesOperationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True, help_text='Shifter operation correlation key')),
                ('range_id', models.UUIDField(blank=True, db_index=True, help_text='Optional range projection/backfill key; not the operation key', null=True)),
                ('operation_id', models.CharField(db_index=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('contract_kind', models.CharField(choices=[('aces', 'ACES')], default='aces', max_length=32)),
                ('contract_version', models.CharField(db_index=True, max_length=64)),
                ('contract_profile', models.CharField(db_index=True, max_length=64)),
                ('record_kind', models.CharField(choices=[('operation_receipt', 'Operation receipt'), ('operation_status', 'Operation status'), ('runtime_snapshot', 'Runtime snapshot'), ('execution_plan_ref', 'Execution-plan reference')], db_index=True, max_length=32)),
                ('source_timestamp', models.DateTimeField(db_index=True)),
                ('payload_digest', models.CharField(max_length=71)),
                ('payload', models.JSONField(default=dict, help_text='Validated canonical ACES payload or bounded reference payload')),
                ('diagnostic_refs', models.JSONField(blank=True, default=dict, help_text='Sanitized diagnostic references only; no provider dumps, tokens, or embedded output')),
                ('owner', models.CharField(choices=[('shared', 'Shared ACES boundary'), ('engine', 'Engine service'), ('provisioner', 'Provisioner'), ('cms', 'CMS service')], db_index=True, default='shared', max_length=32)),
                ('retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_aces_operation_record',
                'ordering': ['-source_timestamp', '-created_at'],
                'indexes': [models.Index(fields=['request_id', 'record_kind', 'source_timestamp'], name='acesop_req_kind_src_idx'), models.Index(fields=['operation_id', 'record_kind'], name='acesop_op_kind_idx'), models.Index(fields=['retention_expires_at'], name='acesop_retention_idx')],
                'constraints': [models.UniqueConstraint(fields=('request_id', 'record_kind', 'contract_version', 'contract_profile', 'idempotency_key'), name='uniq_acesop_idempotency')],
            },
        ),
    ]
