# Generated by Django 6.0.6 on 2026-07-06 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_acesoperationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcesParticipantRuntimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True, help_text='Shifter operation correlation key')),
                ('range_id', models.UUIDField(blank=True, db_index=True, help_text='Optional range projection/backfill key; not the participant identity', null=True)),
                ('range_instance_id', models.UUIDField(blank=True, db_index=True, help_text='Optional range-instance projection/backfill key; not the participant identity', null=True)),
                ('participant_ref', models.CharField(db_index=True, help_text='Bounded participant correlation reference; never alone the identity', max_length=256)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('contract_kind', models.CharField(choices=[('aces', 'ACES')], default='aces', max_length=32)),
                ('contract_version', models.CharField(db_index=True, max_length=64)),
                ('contract_profile', models.CharField(db_index=True, max_length=64)),
                ('participant_runtime_profile', models.CharField(db_index=True, max_length=64)),
                ('record_kind', models.CharField(choices=[('participant_implementation', 'Participant implementation'), ('participant_runtime', 'Participant runtime')], db_index=True, max_length=32)),
                ('source_timestamp', models.DateTimeField(db_index=True)),
                ('payload_digest', models.CharField(max_length=71)),
                ('payload', models.JSONField(default=dict, help_text='Validated canonical ACES participant-runtime payload or bounded reference payload')),
                ('diagnostic_refs', models.JSONField(blank=True, default=dict, help_text='Sanitized diagnostic references only; no provider dumps, tokens, or embedded output')),
                ('owner', models.CharField(choices=[('shared', 'Shared ACES boundary'), ('engine', 'Engine service'), ('provisioner', 'Provisioner'), ('cms', 'CMS service'), ('ctf', 'CTF service')], db_index=True, default='shared', max_length=32)),
                ('retention_class', models.CharField(choices=[('default', 'Default retention')], default='default', max_length=32)),
                ('retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('redaction_state', models.CharField(choices=[('sanitized', 'Sanitized')], default='sanitized', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_aces_participant_runtime_record',
                'ordering': ['-source_timestamp', '-created_at'],
                'indexes': [models.Index(fields=['request_id', 'record_kind', 'source_timestamp'], name='acespr_req_kind_src_idx'), models.Index(fields=['participant_ref', 'record_kind'], name='acespr_ref_kind_idx'), models.Index(fields=['retention_expires_at'], name='acespr_retention_idx')],
                'constraints': [models.UniqueConstraint(fields=('request_id', 'participant_ref', 'record_kind', 'participant_runtime_profile', 'contract_version', 'idempotency_key'), name='uniq_acespr_idempotency')],
            },
        ),
    ]
