# Generated by Django 6.0.6 on 2026-07-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_acesparticipantruntimerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesparticipantruntimerecord',
            name='record_kind',
            field=models.CharField(choices=[('participant_implementation', 'Participant implementation'), ('participant_runtime', 'Participant runtime'), ('participant_behavior_history', 'Participant behavior history'), ('participant_evidence', 'Participant evidence')], db_index=True, max_length=32),
        ),
    ]
