# Generated by Django 6.0.6 on 2026-07-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_raes_hard_cutover_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('apikey', 'API Key'), ('range', 'Range'), ('credential', 'Credential'), ('agent', 'Agent'), ('user', 'User'), ('session', 'Session'), ('ngfw', 'NGFW'), ('config', 'Configuration'), ('experiment', 'Experiment'), ('scenario', 'Scenario'), ('script', 'Script'), ('workspace_membership', 'Workspace Membership')], max_length=20),
        ),
    ]
