# Generated by Django 6.0.6 on 2026-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_alter_auditlog_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('restore', 'Restore'), ('close', 'Close'), ('reopen', 'Reopen'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('access_denied', 'Access Denied'), ('role_sync', 'Role Sync'), ('connect', 'Connect'), ('disconnect', 'Disconnect'), ('download', 'Download'), ('provision', 'Provision'), ('deprovision', 'Deprovision'), ('ready', 'Ready'), ('failed', 'Failed'), ('pause', 'Pause'), ('resume', 'Resume'), ('cancel', 'Cancel'), ('recover', 'Recover'), ('spare_provision', 'Spare Provision'), ('capacity_assess', 'Capacity Assess')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('apikey', 'API Key'), ('range', 'Range'), ('credential', 'Credential'), ('agent', 'Agent'), ('user', 'User'), ('session', 'Session'), ('ngfw', 'NGFW'), ('config', 'Configuration'), ('experiment', 'Experiment'), ('scenario', 'Scenario'), ('script', 'Script'), ('workspace_membership', 'Workspace Membership'), ('workspace', 'Workspace'), ('organization', 'Organization')], max_length=20),
        ),
    ]
