# Generated by Django 6.0.8 on 2026-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_alter_auditlog_action_alter_auditlog_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('apikey', 'API Key'), ('range', 'Range'), ('credential', 'Credential'), ('agent', 'Agent'), ('user', 'User'), ('session', 'Session'), ('ngfw', 'NGFW'), ('config', 'Configuration'), ('experiment', 'Experiment'), ('scenario', 'Scenario'), ('script', 'Script'), ('workspace_membership', 'Workspace Membership'), ('workspace_invitation', 'Workspace Invitation'), ('workspace', 'Workspace'), ('organization', 'Organization')], max_length=20),
        ),
    ]
