# Generated by Django 6.0.8 on 2026-09-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('archive', 'Archive'), ('restore', 'Restore'), ('close', 'Close'), ('reopen', 'Reopen'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('access_denied', 'Access Denied'), ('role_sync', 'Role Sync'), ('connect', 'Connect'), ('disconnect', 'Disconnect'), ('download', 'Download'), ('provision', 'Provision'), ('deprovision', 'Deprovision'), ('ready', 'Ready'), ('failed', 'Failed'), ('pause', 'Pause'), ('resume', 'Resume'), ('cancel', 'Cancel'), ('recover', 'Recover'), ('spare_provision', 'Spare Provision'), ('capacity_assess', 'Capacity Assess'), ('quota_applied', 'Quota Applied'), ('warm_prepare', 'Warm Prepare'), ('warm_claim', 'Warm Claim'), ('warm_fallback', 'Warm Fallback'), ('warm_activate', 'Warm Activate'), ('warm_retire', 'Warm Retire')], max_length=20),
        ),
    ]
