apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-runtime
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.runtimeEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
