{{- $runtimeEnv := deepCopy .Values.runtimeEnv -}}
{{- $_ := set $runtimeEnv "ENGINE_TASK_NAMESPACE" .Values.namespaces.jobs -}}
{{- $_ = set $runtimeEnv "ENGINE_TASK_SERVICE_ACCOUNT_NAME" .Values.serviceAccounts.provisioner.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-runtime
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
data:
  {{- range $key, $value := $runtimeEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
