apiVersion: v1
kind: Service
metadata:
  name: guacamole-client
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: guacamole-client
  {{- with .Values.services.guacamoleClient.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: shifter
    app.kubernetes.io/component: guacamole-client
  ports:
    - name: http
      port: 8080
      targetPort: http
