apiVersion: v1
kind: Service
metadata:
  name: guacamole-client
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: guacamole-client
  {{- if or .Values.services.guacamoleClient.annotations .Values.services.guacamoleClient.backendConfig.enabled }}
  annotations:
    {{- with .Values.services.guacamoleClient.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.services.guacamoleClient.backendConfig.enabled }}
    cloud.google.com/backend-config: {{ dict "default" .Values.services.guacamoleClient.backendConfig.name | toJson | quote }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: shifter
    app.kubernetes.io/component: guacamole-client
  ports:
    - name: http
      port: 8080
      targetPort: http
