{{- $ingress := .Values.edge.ingress -}}
{{- if $ingress.enabled }}
{{- if and .Values.capabilities.gcpManagedTls $ingress.host $ingress.gcpManagedTls.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $ingress.gcpManagedTls.frontendConfigName }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: TEMPORARY_REDIRECT
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ $ingress.gcpManagedTls.certificateName }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
spec:
  domains:
    - {{ $ingress.host | quote }}
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-external
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
  {{- if or $ingress.annotations (and .Values.capabilities.gcpManagedTls $ingress.gcpManagedTls.enabled) }}
  annotations:
    {{- with $ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.capabilities.gcpManagedTls $ingress.host $ingress.gcpManagedTls.enabled }}
    networking.gke.io/managed-certificates: {{ $ingress.gcpManagedTls.certificateName | quote }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $ingress.gcpManagedTls.frontendConfigName | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className | quote }}
  {{- end }}
  {{- if and $ingress.tls.enabled $ingress.host }}
  tls:
    - hosts:
        - {{ $ingress.host | quote }}
      secretName: {{ $ingress.tls.secretName | quote }}
  {{- end }}
  defaultBackend:
    service:
      name: portal-web
      port:
        number: 8000
  rules:
    - {{- if $ingress.host }}
      host: {{ $ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: /guacamole
            pathType: Prefix
            backend:
              service:
                name: guacamole-client
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-web
                port:
                  number: 8000
{{- end }}
