{{- if .Values.guacamoleRuntimeSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.guacamoleRuntimeSecret.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.guacamoleRuntimeSecret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
