apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.portal.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal
  {{- with .Values.serviceAccounts.portal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.workers.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: workers
  {{- with .Values.serviceAccounts.workers.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.ctfScheduler.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: ctf-scheduler
  {{- with .Values.serviceAccounts.ctfScheduler.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.provisioner.name }}
  namespace: {{ .Values.namespaces.jobs }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
  {{- with .Values.serviceAccounts.provisioner.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
