{{- $portalAnnotations := deepCopy .Values.serviceAccounts.portal.annotations -}}
{{- with (index .Values.identity.serviceAccountRoleArns "portal") -}}
{{- $_ := set $portalAnnotations "eks.amazonaws.com/role-arn" . -}}
{{- end -}}
{{- $workerAnnotations := deepCopy .Values.serviceAccounts.workers.annotations -}}
{{- with (index .Values.identity.serviceAccountRoleArns "workers") -}}
{{- $_ := set $workerAnnotations "eks.amazonaws.com/role-arn" . -}}
{{- end -}}
{{- $schedulerAnnotations := deepCopy .Values.serviceAccounts.ctfScheduler.annotations -}}
{{- with (index .Values.identity.serviceAccountRoleArns "ctfScheduler") -}}
{{- $_ := set $schedulerAnnotations "eks.amazonaws.com/role-arn" . -}}
{{- end -}}
{{- $launcherAnnotations := deepCopy .Values.serviceAccounts.provisionerLauncher.annotations -}}
{{- with (index .Values.identity.serviceAccountRoleArns "provisionerLauncher") -}}
{{- $_ := set $launcherAnnotations "eks.amazonaws.com/role-arn" . -}}
{{- end -}}
{{- $provisionerAnnotations := deepCopy .Values.serviceAccounts.provisioner.annotations -}}
{{- with (index .Values.identity.serviceAccountRoleArns "provisioner") -}}
{{- $_ := set $provisionerAnnotations "eks.amazonaws.com/role-arn" . -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.portal.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal
  {{- with $portalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.workers.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: workers
  {{- with $workerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.ctfScheduler.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: ctf-scheduler
  {{- with $schedulerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.capabilities.kubernetesJobLauncher }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.provisionerLauncher.name }}
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner-launcher
  {{- with $launcherAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.provisioner.name }}
  namespace: {{ .Values.namespaces.jobs }}
  labels:
    {{- include "shifter.partOfLabels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
  {{- with $provisionerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
