"""Check for cross-layer ForeignKey relationships between models.

This management command inspects Django models across the platform's
service layers and detects FK/OneToOne/M2M relationships that cross
layer boundaries in the wrong direction.

## Layer Hierarchy

  - shared (0)        - lowest, common utilities
  - engine (1)        - infrastructure provisioning
  - cms (2)           - content management
  - management (3)    - platform administration
  - mission_control (4) - presentation layer (highest)

## Rules

Lower layers should NOT have FKs to higher layers:
  - engine models should not FK to cms, management, mission_control
  - cms models should not FK to management, mission_control
  - etc.

FKs to Django's auth.User are allowed (special case).

Usage:
    python manage.py check_model_fks
    python manage.py check_model_fks --json
    python manage.py check_model_fks -o report.json
"""

import json
import sys

from django.apps import apps
from django.core.management.base import BaseCommand

# Layer hierarchy - index represents position in stack (lower = lower layer)
ALL_LAYERS = ["shared", "engine", "cms", "management", "mission_control"]
LAYER_INDEX = {layer: i for i, layer in enumerate(ALL_LAYERS)}

# Apps that are allowed to be referenced from any layer
ALLOWED_EXTERNAL_APPS = {"auth", "contenttypes", "sessions", "admin"}

# Reverse relation types (auto-generated by Django, not actual FK definitions)
REVERSE_RELATION_TYPES = {"ManyToOneRel", "OneToOneRel", "ManyToManyRel"}


def is_violation(from_layer: str, to_layer: str) -> bool:
    """Check if a FK from from_layer to to_layer is a violation.

    Violations occur when a lower layer has a FK to a higher layer.
    """
    if from_layer not in LAYER_INDEX or to_layer not in LAYER_INDEX:
        return False
    return LAYER_INDEX[from_layer] < LAYER_INDEX[to_layer]


def get_layer_for_app(app_label: str) -> str | None:
    """Map Django app label to layer name."""
    # Direct mapping for our layers
    if app_label in ALL_LAYERS:
        return app_label
    # mission_control might be registered differently
    if app_label == "mission_control":
        return "mission_control"
    return None


class Command(BaseCommand):
    help = "Check for cross-layer ForeignKey violations between models"

    def add_arguments(self, parser):
        parser.add_argument(
            "--json",
            action="store_true",
            help="Output results as JSON",
        )
        parser.add_argument(
            "-o", "--output",
            metavar="FILE",
            help="Save JSON output to file",
        )
        parser.add_argument(
            "-q", "--quiet",
            action="store_true",
            help="Suppress summary output",
        )

    def handle(self, *args, **options):
        results = self.analyze_fks()
        stats = self.compute_stats(results)

        output = {
            "relationships": results,
            "stats": stats,
        }

        # Handle output
        if options["output"]:
            with open(options["output"], "w") as f:
                json.dump(output, f, indent=2)
            self.stderr.write(f"Output saved to {options['output']}")

        if options["json"] or options["output"]:
            if not options["output"]:
                self.stdout.write(json.dumps(output, indent=2))

        # Print summary unless quiet
        if not options["quiet"]:
            self.print_summary(results, stats)

        # Exit with error if violations found
        if stats["violations"] > 0:
            sys.exit(1)

    def analyze_fks(self) -> dict:
        """Analyze all FK relationships across layers."""
        results = {layer: [] for layer in ALL_LAYERS}

        for layer in ALL_LAYERS:
            try:
                app_config = apps.get_app_config(layer)
            except LookupError:
                continue

            for model in app_config.get_models():
                for field in model._meta.get_fields():
                    # Skip reverse relations (auto-generated by Django)
                    if type(field).__name__ in REVERSE_RELATION_TYPES:
                        continue

                    # Check for relation fields
                    if not hasattr(field, "related_model") or not field.related_model:
                        continue

                    related_app = field.related_model._meta.app_label

                    # Skip allowed external apps
                    if related_app in ALLOWED_EXTERNAL_APPS:
                        continue

                    related_layer = get_layer_for_app(related_app)
                    if not related_layer or related_layer == layer:
                        continue

                    # Record the relationship
                    rel_info = {
                        "model": model.__name__,
                        "field": field.name,
                        "field_type": type(field).__name__,
                        "references": f"{related_layer}.{field.related_model.__name__}",
                        "to_layer": related_layer,
                        "is_violation": is_violation(layer, related_layer),
                    }
                    results[layer].append(rel_info)

        return results

    def compute_stats(self, results: dict) -> dict:
        """Compute summary statistics."""
        stats = {
            "total_cross_layer_fks": 0,
            "violations": 0,
            "clean_layers": [],
            "layers_with_violations": [],
            "violation_details": [],
        }

        for layer, relationships in results.items():
            layer_violations = [r for r in relationships if r["is_violation"]]

            stats["total_cross_layer_fks"] += len(relationships)
            stats["violations"] += len(layer_violations)

            if layer_violations:
                stats["layers_with_violations"].append(layer)
                for v in layer_violations:
                    stats["violation_details"].append({
                        "from": layer,
                        "model": v["model"],
                        "field": v["field"],
                        "references": v["references"],
                    })
            else:
                stats["clean_layers"].append(layer)

        return stats

    def print_summary(self, results: dict, stats: dict):
        """Print human-readable summary."""
        self.stdout.write("\n" + "=" * 50)
        self.stdout.write("MODEL FK SUMMARY")
        self.stdout.write("=" * 50)

        self.stdout.write(f"\nTotal cross-layer FKs: {stats['total_cross_layer_fks']}")
        self.stdout.write(f"Violations: {stats['violations']}")

        self.stdout.write(f"\nClean layers: {', '.join(stats['clean_layers']) or 'none'}")

        if stats["violation_details"]:
            self.stdout.write("\nViolations detected:")
            for v in stats["violation_details"]:
                self.stdout.write(
                    f"  {v['from']}.{v['model']}.{v['field']} -> {v['references']}"
                )
        else:
            self.stdout.write(self.style.SUCCESS("\nNo violations detected!"))

        self.stdout.write("=" * 50 + "\n")
