"""Provider- and scenario-neutral runtime verification plugin seam."""

from .contracts import (
    API_VERSION,
    ENTRY_POINT_GROUP,
    MAX_OUTPUT_BYTES,
    REPORT_SCHEMA_VERSION,
    AdapterCallable,
    AdapterContext,
    AdapterDeclaration,
    AdapterOutcome,
    AdapterStatus,
    Binding,
    CancellationToken,
    CheckReason,
    CheckStatus,
    ExecResult,
    PluginDeclaration,
    Runner,
    RunnerExecutionError,
    VerificationCancelled,
    VerificationDeadlineExceeded,
    equal_without_disclosure,
)
from .discovery import (
    InstalledPlugin,
    LoadedPlugin,
    PluginDiscoveryError,
    PluginSelection,
    discover_plugins,
    load_plugin,
)
from .framework import (
    CheckResult,
    VerificationConfigurationError,
    VerificationReport,
    aggregate_exit_code,
    run_verification,
)
from .report import render_human, render_json

__all__ = [
    "API_VERSION",
    "ENTRY_POINT_GROUP",
    "MAX_OUTPUT_BYTES",
    "REPORT_SCHEMA_VERSION",
    "AdapterCallable",
    "AdapterContext",
    "AdapterDeclaration",
    "AdapterOutcome",
    "AdapterStatus",
    "Binding",
    "CancellationToken",
    "CheckReason",
    "CheckResult",
    "CheckStatus",
    "ExecResult",
    "InstalledPlugin",
    "LoadedPlugin",
    "PluginDeclaration",
    "PluginDiscoveryError",
    "PluginSelection",
    "Runner",
    "RunnerExecutionError",
    "VerificationCancelled",
    "VerificationConfigurationError",
    "VerificationDeadlineExceeded",
    "VerificationReport",
    "aggregate_exit_code",
    "discover_plugins",
    "equal_without_disclosure",
    "load_plugin",
    "render_human",
    "render_json",
    "run_verification",
]
